### ISSUE TITLE
[BUG]:offers and coupons not showing

### ISSUE THREAD

**Issue by mohsinalimat** [yrestom/POS-Awesome#105]
offers and coupons not showing in home screen.

**Comment by mohsinalimat** [comment]
I already create the offers and coupons but not showing in below screen.

![image](https://user-images.githubusercontent.com/973676/148633437-f9e83295-6b13-4118-87d5-0d5060516b75.jpeg)

**Comment by Eslam-Yakout** [comment]
I face the same Problem.

**Comment by yrestom** [comment]
Please check the documentation [here](https://github.com/yrestom/POS-Awesome/wiki/Promotions-and-Offers)

**Comment by 1475963elyus** [comment]
hi sir @yrestom, is there any coupon code function for Pos Awesome ?
