### ISSUE TITLE
Currency Precision

### ISSUE THREAD

**Issue by Freshdigits** [yrestom/POS-Awesome#106]
### Discussed in https://github.com/yrestom/POS-Awesome/discussions/104

<div type='discussions-op-text'>

<sup>Originally posted by **Freshdigits** January  6, 2022</sup>
Hi, 

I need your help to solve an issue in POS-Awesome. In 'Oman' the currency precision is 00.000 i.e three decimal points. we really want your help to make POS-awesome to show three decimal points. even if we make ERPNext precision to three decimal points it's not reflecting there. could you please help me which file should I change for an urgent solution. and I request you to give some settings on POS profile to currency precisions too. really appreciate all your helps and support. 

thank you</div>

**Comment by Freshdigits** [comment]
Hi, 
Any update on this? it would be really appreciable if you implement this feature.. 
Thank you so much

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/f3462da84a05c0323bb9551e6de872f29c73f691

**Comment by Freshdigits** [comment]
> [f3462da](https://github.com/yrestom/POS-Awesome/commit/f3462da84a05c0323bb9551e6de872f29c73f691)

Thank you so much @yrestom .. Really appreciate your help..
