### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by autominded** [yrestom/POS-Awesome#107]
- Erpnext: 
- POS Awesome: 

### Steps to reproduce
So business isnt doing well nowadays and i need to close the shift sometimes with ZERO sales, but POSAwecome wont allow me to close shift with no entries its throwing error of Error: Data missing  in table: POS Awesome.

### Additional context

![image](https://user-images.githubusercontent.com/19249530/148684509-f6b45b2c-e8f7-420f-8fee-e148a51f07ae.png)

**Comment by elan-k** [comment]
Workaround : 

1. Goto "POS Opening Shift" Screen 
2. Cancel the shift opening entry if there is no invoice created using the shift. 

Note: Closing Shift is another DocType that expects the shift should have some invoice. so you can't submit the closing shift without transactions on the shift opening entry.

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/5d1c7e9f7e3c66e2a5ba5c04de284294e7350aec
