### ISSUE TITLE
[Feature Request] Customer Name Should be displayed

### ISSUE THREAD

**Issue by bobzz-zone** [yrestom/POS-Awesome#11]
Hi,

since customer can use series , i think we need to make the customer to be shown on search or while displayed

thanks

**Comment by yrestom** [comment]
I did not understand the idea or use case, please explain further

**Comment by bobzz-zone** [comment]
hmm

the issue is in the tabCustomer
we have the name as CUST-0001 and the customer name PT ABC

so because now its only show the name we can only search and see CUST-00001

thats the problem


thanks

**Comment by yrestom** [comment]
I understand this will be fixed

**Comment by bobzz-zone** [comment]
@yrestom any update on this ?

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/e622986d69c447543124bb411bd02b2ebdda2400
