### ISSUE TITLE
[Feature request]: Document Series for Invoice on POS Profile in V13

### ISSUE THREAD

**Issue by elan-k** [yrestom/POS-Awesome#119]
### Is your feature request related to a problem? Please describe.
In V13, How do I get each of my stores/locations to have a different naming series for their Sales Invoices with this new configuration of the POS Profile?

And it's a very much needed feature for the multistore or business unit environment, this naming series helps to identify the store or business unit from the invoice number for after-sale services. 

like "No of the retail Locations" explained in the Understanding POS Profile (Your wiki document), 
https://github.com/yrestom/POS-Awesome/wiki/Understanding-POS-Profile

### Describe the solution you'd like

We like to have different series available for Sales Invoice (Already defined in the Naming Series for Sales Invoice) as DropDown in the POS Profile to set the default one for that specific POS Profile. 

### Additional context

We have this Naming Series on the POS Profile in V12, But it has been removed from the POS Profile on V13. 

Refer to the "Series" field on the POS Profile in V12,
![image](https://user-images.githubusercontent.com/78781781/152147180-7c38c5c2-a07f-4d9b-9e6b-cfa0dc204487.png)

Examples of Invoice No. 
NB-2022-102

NB - Location Identification (We will use different codes for each store/location) 
2022 - Year 
102 - Serial Number of Sale Invoice

**Comment by elan-k** [comment]
Hi @yrestom ,

Thank you for your reply on this.

 I have tried to add the naming_series on the POS Profile DocType, but was unable to provide or update options on the same. Plz check the image below, 
![image](https://user-images.githubusercontent.com/78781781/152581236-8322f6f2-c131-4d80-88dc-f39d89115c91.png)
It always comes as "Select" on the update or submission on the Customization Page. 

Plz refer to the POS Profile screen, 
![image](https://user-images.githubusercontent.com/78781781/152582705-1ed955a7-312d-467d-af68-2067e9bf148e.png)
 
Also, Even when we create the custom field "naming_series" on the POS Profile, how this will affect the respective sales invoice creation while using the Awesome POS. 

@yrestom : Please help us to understand and bring different series of sales invoices for each POS profile.

**Comment by yrestom** [comment]
The field type should be "Data", and if you want it like it was before, try to do customization on POS Profile to get that functionality back, it should work without any need for additional POS customization.

**Comment by elan-k** [comment]
While making the custom field using DATA as a field type, we are receiving the following error message on the save,

![image](https://user-images.githubusercontent.com/78781781/152733966-4679d0e8-fb2e-49d1-b9cf-5a4167d40133.png)

Looks like V13 is limiting the usage of DATA field type to "Email, Phone, URL, BarCode & Name" fields only and it's related to default validation it seems. 

But I haven't mentioned anything over OPTIONS there for validation, 
![image](https://user-images.githubusercontent.com/78781781/152735799-b97d9397-491a-4895-ace4-6258f2de4096.png)

So I have tried using "SMALL TEXT" as Field Type, but [Select] get into the options automatically while saving the changes. 
![image](https://user-images.githubusercontent.com/78781781/152736985-f8ab2878-3ea5-49f0-8d4a-9034036ff5b5.png)

Any workaround for this issue?

**Comment by yrestom** [comment]
Delete that field and create a new one with the type "Select" and put the options for series manually

**Comment by elan-k** [comment]
Now It works well, got the sales invoice number configurable on the POS Profile as it's much needed for multi-location businesses.

On Customization, 
![image](https://user-images.githubusercontent.com/78781781/153162162-4237cddd-e551-4111-b1ef-d6a8f53b957e.png)

User Screen on the POS Profile, 
![image](https://user-images.githubusercontent.com/78781781/153162723-a086e298-2159-4b94-903f-516be2fd8e52.png)


Great Work by @yrestom
