### ISSUE TITLE
[Feature request]:  Accept Payment of previous Credit Sales on POS Awesome

### ISSUE THREAD

**Issue by ardentpros** [yrestom/POS-Awesome#124]
### Describe the solution you'd like

Making it possible to create payment entry for previous credit sales done for selected customers while in POS Awesome i.e. accepting payment on a customer account to clear the outstanding debt before issuing a new sales invoice.

**Comment by yrestom** [comment]
This feature is in the plan, but not soon

**Comment by mujeerhashmi** [comment]
same as #116
