### ISSUE TITLE
[BUG]: POS can't make Sales Order if the item quantity is 0

### ISSUE THREAD

**Issue by winchai** [yrestom/POS-Awesome#128]
### Versions

ERPNext: v13.19.0 (version-13)

Frappe Framework: v13.19.0 (version-13)

POS Awesome: v3.1.1 (master)

### Steps to reproduce

1. Go to Pos and ensure create sales order is enabled on the selected pos Profile
2. Change type from invoice to order
3. Add to card Item with 0 Quantity
4. and Then Click Pay , it will show error " The Existing quantity '0' for item is not enough"

### What is Expected?
since sales order transaction need to be delivered at a certain date , the quantity shouldn't be the problem for now , but the error exist saying the quanity is 0 ,what i expect is we should be able to submit the payment

### What is actually happening?
error "The Existing quantity '0' for item is not enough"

### Screenshots
<img width="640" alt="POSAWESOMEBUG 3" src="https://user-images.githubusercontent.com/58699787/153691725-4ccd64c7-75db-4bfe-b4f1-8247a1351d62.png">

<img width="1083" alt="POSAWESOMEBUG 2" src="https://user-images.githubusercontent.com/58699787/153691690-33268fe3-862b-4763-893f-d55894635d22.png">

**Comment by yrestom** [comment]
[fix: POS can't make Sales Order if there is no stock](https://github.com/yrestom/POS-Awesome/commit/04eb8dede1fa8da4e85b32cab4c3d33eaf644b46)

**Comment by winchai** [comment]
Thank you very much , you help me a lot Mr Yousef , GBU
