### ISSUE TITLE
[Bug] Number Format

### ISSUE THREAD

**Issue by bobzz-zone** [yrestom/POS-Awesome#13]
Hi,

i see that the number on the pirce not fomatted , it should formatted so it will shown separator
ex : 100000 -> 100.000

thanks

**Comment by yrestom** [comment]
This will be fixed in the next version

**Comment by Botanium** [comment]
this number format is annoying. when exactly the next version will be out?

**Comment by yrestom** [comment]
I am waiting for the stable release of Erpnext 13 because it has a lot of drastic changes as you know

**Comment by bobzz-zone** [comment]
@yrestom i think its better to update the v12 first.. i think it will be quite long time for v13

**Comment by yrestom** [comment]
@bobzz-zone You're right, I'll try to fix it sooner, thank you

**Comment by olamide2** [comment]
Helo @yrestom 

When will this be fixed? It is really annoying

**Comment by yrestom** [comment]
fixed: https://github.com/yrestom/POS-Awesome/commit/e4b1c1208e90ff262be89dae11b576a8b78d2e6a
