### ISSUE TITLE
[Feature request]: Make Sales Order Type the Default One , instead of Invoice Type

### ISSUE THREAD

**Issue by winchai** [yrestom/POS-Awesome#131]
Dear Mr Yousef , 

Everytime i open the Pos , the Invoice Type always the default one , can we change it to Order Type for the Default one?

Thanks

**Comment by muchai** [comment]
This is available now, right?

![image](https://user-images.githubusercontent.com/1822868/230468017-f116cf76-4b46-43a7-be8a-b63282d797f1.png)

**Comment by yrestom** [comment]
[feat: Options for Default Card View & Default Sales Order](https://github.com/yrestom/POS-Awesome/commit/a79bc0211bb99e86cd7001c13a6452184fc59163)
