### ISSUE TITLE
[BUG]:  Customer Info Dialog - Not Showing Customer Name and Editing Customer Details Throws Error

### ISSUE THREAD

**Issue by dmbabu** [yrestom/POS-Awesome#132]
### Versions

- Frappe: 13.19.0
- Erpnext: 13.19.0
- POS Awesome: 3.1.1

### Stacktrace / full error message

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
TypeError: set_customer_info() missing 1 required positional argument: 'customer'

### Steps to reproduce

1. In POS Awesome, Click Customer Info button (icon before to Customer)
2. Customer Info dialog will open to show customer info.
3. Customer Name field is not populated.
4. Typing in any editable field results in error 'TypeError: set_customer_info() missing 1 required positional argument: 'customer''

### What is Expected?

Display customer name and other info. If editing customer info here brings complications, make fields read only

### What is actually happening?

Customer name is not displayed. Typing on email and mobile no fields throws an exception.

### Additional context
None

### Screenshots
![Customer Info2](https://user-images.githubusercontent.com/45001106/153703354-5c0ce5f2-82ec-42d9-a4db-ad76c79ace8d.png)

**Comment by yrestom** [comment]
[fix: customer info dialog not showing customer name](https://github.com/yrestom/POS-Awesome/commit/d379cf7b6e919b0a981c1e9147f7ee4719a21328)
