### ISSUE TITLE
[BUG]: Stock Balance Become 0 after Invoice Cancelled 

### ISSUE THREAD

**Issue by elan-k** [yrestom/POS-Awesome#135]
Available Stock Value for the specific item becomes zero (0) when we cancel the invoice. 

Getting this error message on the PAY button, 

The existing quantity '0' for item 'Item ABCD' is not enough

### Steps to reproduce

1. Create an Invoice using [POS-Awesome](https://github.com/yrestom/POS-Awesome) 
2. Go to Sales Invoice Screen On ERPNext and Cancel the Invoice 
3. Come back to the [POS-Awesome](https://github.com/yrestom/POS-Awesome) 
4. Try to make an invoice using the same item again
5. At Pay Button Click, The existing quantity '0' for item 'Item ABCD' is not enough

### What is Expected?

Stock values should be updated correctly on the  [POS-Awesome](https://github.com/yrestom/POS-Awesome), so that we should be able to make the invoice again using the same item. 

Note: Tried after refreshing the page as well. But this issue will be over after a couple of hours as per my observation.

### What is actually happening?

Batch No Available QTY is uncharged and Available QTY becomes 0 irrespective of the stock value after the cancellation of the invoice. So it stops us from completing the invoice on [POS-Awesome](https://github.com/yrestom/POS-Awesome)

At the same time, we will be able to make regular sales invoices (Not POS)  from the sales invoice screen on ERPNext and we are able to see the available batch qty and available qty in the warehouse correctly. 

### Additional context

1. Tried after multiple refreshes & Reload 
2. Checked the Stock Ledger Report, which is showing correctly.

### Screenshots

Stock Issue on the POS, 
![Stock_Related_Error_POS AWESOME](https://user-images.githubusercontent.com/78781781/155221937-7a58bc75-d86a-4f3b-8c45-14a3e6fb2bdb.png)

Correct Stock Details on Sales Invoice Screen, 
![Stock_Related_Sales_Invoice_screen](https://user-images.githubusercontent.com/78781781/155222192-f1c8bc10-3b79-4533-86da-97029475ccdd.png)

### Versions

ERPNext: v13.20.1 (HEAD)
Frappe Framework: v13.20.1 (HEAD)
POS Awesome: v3.1.1 (HEAD)

**Comment by bkm888** [comment]
I am also finding this to be a problem using POS Awesome v3.2.1 (master)

BKM

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/29472c7d43d2df745bf73893bbc51e57a55167a9
