### ISSUE TITLE
Item groups not being feed to the product list

### ISSUE THREAD

**Issue by EddieDee** [yrestom/POS-Awesome#14]
For a given item group tree as this one:

All Item Groups
   Group 1
   Group 2
   Group 3

If you have in the POS Profile "All Item Groups" as the item group where items should be loaded, its not taking in to account the sub groups.. So all items under Group 1, Group 2, Group 3

Regards,

**Comment by yrestom** [comment]
It will be fixed soon

**Comment by olamide2** [comment]
Hello @yrestom 

Is this fixed yet?

**Comment by Botanium** [comment]
This bug is a stopper for me. Is there a way to fix it, please? It is very urgent.

**Comment by CloudERPng** [comment]
Hi @yrestom  any update on this?

**Comment by yrestom** [comment]
[fix: Item groups not being feed to the product list](https://github.com/yrestom/POS-Awesome/commit/a4925842c0ee451c70e1b92a08bc676480fee712)
