### ISSUE TITLE
[Feature request]: Collecting Customer Address Details within the POS 

### ISSUE THREAD

**Issue by elan-k** [yrestom/POS-Awesome#142]
### Is your feature request related to a problem? Please describe.
1. Unable to add customer along with Address Details
2. The address is very much needed in terms of delivery (Phone Orders, 3rd Party Website Orders, etc) 
3. Every time, the POS Screen has to be refreshed when we add a customer along with the address outside the POS. 

![image](https://user-images.githubusercontent.com/78781781/162169804-f2e6b57e-1c40-4a40-9812-af77461a23d0.png)

### Describe the solution you'd like

1. Option to add address details on the New Customer Screen 
         1. Address Line 1
         2. Address Line 2
         3. City 
         4. Zip Code 
2. In POS Profile, the option to set the Default Value for the following fields from the New Customer Screen
         1. City
         2. Country (may not require on the POS Screen, but useful in terms of saving address DocType) 
         3. Customer Group 
         4. Territory
         
These options will enhance the usability of the POS and help the cashier to complete the transaction much faster. 

### Additional context

Nowadays, there are a lot of different hyperlocal platforms which offer merchants to sell online and deliver their products to the customer's place. And the delivery service becomes a must-have option for a physical store.  

**Installed Version**
Frappe Framework: v13.23.0 (HEAD)
ERPNext: v13.23.3 (HEAD)
POS Awesome: v3.2.1 (HEAD)

**Comment by yrestom** [comment]
This feature already exists but it works differently 
https://github.com/yrestom/POS-Awesome/wiki/Making-Sales-Orders
<img width="1150" alt="Screen Shot 2022-04-07 at 16 02 19" src="https://user-images.githubusercontent.com/19572067/162204934-10b6af00-67c2-4218-b209-e79e63aaf135.png">
