### ISSUE TITLE
[BUG]: Item Price change ignored if set to zero.

### ISSUE THREAD

**Issue by bkm888** [yrestom/POS-Awesome#143]
BUG Description:

When editing the Item Rate of an Item in the cart, if you set the rate to zero in order to give the Item away, the Pay screen does not reflect the change and leaves the Item at full price. However, if you set the rate to anything other than zero it works properly.

### Versions

- Frappe: V13.11.0
- Erpnext:  V13.11.1
- POS Awesome: V3.2.1

### Steps to reproduce

1. Open POS Awesome using a POS Profile that allows editing the Item Rate
2. Add an Item to the cart
3. Edit the rate of the Item to 0.00
4. Click the PAY button
5. Notice the Amount to be paid is set to full price of the Item plus taxes and charges.
6. Click the BACK button 
7. Edit the Item Rate to be 0.01
8. Click the PAY button
9. Notice the amount to be paid is 0.01 (as expected) 

### What is Expected?

When the Item Rate is edited, the edited amount should carry over correctly to the payment side of the screen. (see steps above)

### What is actually happening?

When editing Item Amount to 0.00 it is ignored on the payment side of the screen and full price payment is expected.

### Additional context

Important to use a POS Profile that allows editing of the rate and being able to set the discount to 100%

This error is likely an issue with a Zero being mistaken for a 'blank' or 'null' in context.

### Screenshots
![POSzerorate1](https://user-images.githubusercontent.com/30693364/162262004-9655cc76-8776-4f54-bcac-fd2931ed5cab.jpg)

![POSzerorate2](https://user-images.githubusercontent.com/30693364/162262042-be5ea9dc-b2b9-420d-b1b5-173fb977d86d.jpg)

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/1e70ef76a9288890c3a718a6764a748e61bd7dd6
