### ISSUE TITLE
[Feature request]: Need a way to add the same item to the cart 2 times on 2 different lines.

### ISSUE THREAD

**Issue by bkm888** [yrestom/POS-Awesome#144]
As a small business owner, it is important to be able to make on-the-spot promotions in order to close a deal with a customer of a competitor and win their business. As an aggressive sales team, I give them the flexibility to give away any product if it wins us a long term relationship.

To that end...
I need to be able to give away multiples of an Item on one line of the sales cart while also charging full price for the same item on a different line.

For example: 
I go into a business that cleans office buildings and they are a client of my competitor. I convince them to buy from me a 5 gallon bucket of concentrated floor cleaner and to use it right away to give me feedback.
While I am standing there I see that there are 3 new buckets of my competitors similar product there. In order to get them to use my product and get locked in for a long time with my product, I offer to replace all 3 of the competitors buckets with 3 of mine and then to make it worth their time I offer to also add another free bucket it they agree to buy just one.
In this scenario, I have wiped out my competitors stock-pile hold on the client by taking the competitive product away, I have sweetened the deal by giving them an extra bucket of product, and I have sold them one bucket of product. 

The result is that I need one line on the cart for the bucket of product I sold...
And another line for the 4 buckets I gave away.

Under the current POS Awesome, every instance of the product I add to the cart just increases the number of the items on the line for the Item in the cart.

What I need:

I need a way to separate on the cart (and therefore on the printed receipt) a way to have multiple lines for the exact same Item but each at different prices.

Things I have considered as solutions:

1. I considered making promotions that give away products, but those have to be done BEFORE I even get in front of a customer. That would not solve the problem of the use case I described above.
2. I tried adjusting the Item Rate to reflect paying for only one item, but that doesn't work because it essentially divides the rate by the total number of Items delivered.
3. Nothing seems to have the same psychological value as seeing multiple items on a receipt that were free. 

Final thoughts on this...

I could not really figure out a way to do this on the spur-of-the-moment while in front of a potential client. The flexibility to give away any product has been a huge driver of long customer relationships for us over the past 3 years. So, any assistance it finding a way to get that psychological advantage on the final printed receipt would be appreciated.

A possible "suggestion" for a way to differentiate lines in the cart that can be duplicated. Maybe add a field to the ITem that is a radio button or other similar acting marker to indicate if a line item is a "Spot Promo" which would mean that it is on a line by itself and would allow other Items of the saem Item code to occupy a new line in the cart. See screenshot below:

![Suggestion](https://user-images.githubusercontent.com/30693364/162270704-bdd097bf-eb0f-492b-af31-667b2dbdc9d7.jpg)

Thank you

**Comment by CloudERPng** [comment]
Hi @bkm888 

This looks like a good idea that can be controlled from PoS Profile

I second it

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/ed52f3f3d3b77bfae27476f3254dea1399af4a14
