### ISSUE TITLE
[BUG]: js/toConsole.min.js and js/posapp.min.js not found

### ISSUE THREAD

**Issue by martuico** [yrestom/POS-Awesome#145]
Having some issues on running POS system it doesn't build upon installation.

### Versions
- Frappe: v14.x.x-develop () (develop)
- Erpnext: v14.x.x-develop () (develop)
- POS Awesome: v3.2.1 (master)

### Stacktrace / full error message
02:28:27 web.1            | 127.0.0.1 - - [13/Apr/2022 02:28:27] "GET /assets/js/toConsole.min.js HTTP/1.1" 404
02:28:27 web.1            | 127.0.0.1 - - [13/Apr/2022 02:28:27] "GET /assets/js/posapp.min.js HTTP/1.1" 404 

### Steps to reproduce
Followed installation instrunction

bench get-app https://github.com/yrestom/POS-Awesome.git
bench setup requirements
bench build --app posawesome
bench restart
bench --site [your.site.name] install-app posawesome
bench --site [your.site.name] migrate

### Screenshots

<img width="806" alt="Screen Shot 2022-04-13 at 2 09 59 AM" src="https://user-images.githubusercontent.com/2949921/163028629-e3191c01-5dc2-4c9f-af33-3ebd83ff3780.png">

**Comment by yrestom** [comment]
It is not optimized yet for Erpnext version 14
