### ISSUE TITLE
[BUG]: After Paying the Available quantity is not auto Update, it is updated only after manually refreshing the page

### ISSUE THREAD

**Issue by SPriytesh** [yrestom/POS-Awesome#148]
After doing a transaction using POSAwesome and doing the payment it should auto update the Available quantity of the Item in inventory and the POS page but it is not happening. Instead I have to refresh the page in order to get the latest Available quantity. Can anyone resolve this as when we do any transaction it should auto update the Actual quantity in the POS page and we do not require to refresh the page.
Thanks

**Comment by yrestom** [comment]
Currently, it updates the available quantities when searching for a product or when adding it to the card
