### ISSUE TITLE
[BUG]: Item not showing on POS search

### ISSUE THREAD

**Issue by sudeshmadu** [yrestom/POS-Awesome#149]
- Erpnext: 
- POS Awesome: 

### Additional context
When i try to add some product to POS awsome by searching on search bar, it's not showing. But i have stock from this product. I have searched with deferent methods like Product code, Product name & Serial numbers. But i can't find this product in POS Awsome. For now i found only one product with this error. I don't know there is more or not. Anyway i can create sales invoice with this product. There is no problem with sales invoice. Please help me on this.

![22Capture](https://user-images.githubusercontent.com/104251844/164886890-762499b2-add9-41dd-a41d-558aaa8cd7a5.PNG)
![21Capture](https://user-images.githubusercontent.com/104251844/164886887-8502383b-7ffb-45b0-856b-ec08ea1b72ab.PNG)

**Comment by yrestom** [comment]
Which app versions are you using?

**Comment by sudeshmadu** [comment]
> 

POS Awsome 3.2.1

**Comment by sudeshmadu** [comment]
I have just check right now. It's automatically fixed. I don't know how.
