### ISSUE TITLE
Invoice status label

### ISSUE THREAD

**Issue by EddieDee** [yrestom/POS-Awesome#15]
I will like to know when I am working with invoices as draft, unpaid or return which is not clear.

PS.: I don't know why invoices are getting saved as unpaid..

**Comment by yrestom** [comment]
That's right, it must be clarified, I will support it in the next version.

**Comment by olamide2** [comment]
Hello @yrestom 

Any update on this?

**Comment by EddieDee** [comment]
Hi @yrestom! Hope you are doing very well, do you know if this is already implemented?
