### ISSUE TITLE
[BUG]: Split Payment POS sale generates "Unpaid" Sales Invoice

### ISSUE THREAD

**Issue by bkm888** [yrestom/POS-Awesome#154]
### Versions

- Frappe: 13.11.1
- Erpnext: 13.11.0
- POS Awesome: 3.2.1  &  3.2.2

### Steps to reproduce

Prerequisite: must have 4 payment types:
Cash, Credit Card, Check, On Account

1. Go to POS Awesome and start a sales transaction with a customer and an Item in the cart to equal total of approx $47.00
2. Click on PAY
3. In the "Check" payment amount put a partial payment of aprox $15.00
4. In the "Cash" payment amount put a payment of $50.00
5. Click Submit Payment
6. Print receipt

### What is Expected?

Receipt prints as expected and the amount on the receipt look correct.

However, if you look at the Sales Invoice generated by this transaction, ERPNext lists it as "Unpaid"

A separate payment entry must be made to close the sale.

See screenshots below:

![POS split-pay-error](https://user-images.githubusercontent.com/30693364/167447924-5624606e-8211-4859-9bc7-95617993dcdb.jpg)

![POS split-pay-error-receipt](https://user-images.githubusercontent.com/30693364/167449027-fe2e71ba-ed85-4d18-82b4-4697c3aed48a.jpg)

![POS split-pay-Sales_Invoice](https://user-images.githubusercontent.com/30693364/167449084-d15db5c6-7180-4a10-8fbd-f8be22d693a8.jpg)

After having a look at the database, it appears that when the split payment sale is generated by POS Awesome, it populates the "Outstanding Balance" field in the Sales Invoice with the "Change Amount" from the transaction.

While this may not be the only cause of the problem, it is at least a start in the right direction.

BKM

**Comment by bkm888** [comment]
Edited the BUG report to include the sentences at the end about populating the Outstanding Balance field incorrectly.

BKM

**Comment by yrestom** [comment]
Unfortunately, I can't replicate this bug
Can you provide me with any additional information that helps ?

**Comment by bkm888** [comment]
Yousef,
 
I have made one of my sandbox servers available to you. You should be able to duplicate the error on this server.
 
URL:   test2.matoddjr.com
IP Add:  192.227.193.161
 
ERPNext Administrator password:  Y0usefPOS
User1: ***@***.***   Password: Y0usefPOS
User2: ***@***.***   Password: Y0usefPOS
(either of the regular users will work with POS Awsome. They both are part of the same POS Profile)
 
Root password for the server: Y0usefPOS
 
ERPNext install account user: erp_jmi         Password: Y0usefPOS
 
 
With the above credentials you can do anything to this server. If it gets corrupted, I can build it again so, no problems.
 
Using the instructions in the Github issue you shoudl be able to directly replicate the issue on this server.
 
Let me know if you would need anything else.
 
Bryan Miles
JMI Barcodes
 
 
 
-----Original Message-----
From: "Yousef Restom" ***@***.***
Date: 05/10/2022 03:01 PM
To: "yrestom/POS-Awesome" ***@***.***>
CC: "bkm888" ***@***.***>, "Author" ***@***.***>
Subject: Re: [yrestom/POS-Awesome] [BUG]: Split Payment POS sale generates "Unpaid" Sales Invoice (Issue #154)


Unfortunately, I can't replicate this bug
Can you provide me with any additional information that helps ?—

**Comment by bkm888** [comment]
Will send you a personal email with the login credentials for one of my sandbox servers to test this issue.

BKM

**Comment by yrestom** [comment]
That's will be better 😉

**Comment by bkm888** [comment]
Email sent !!!

BKM
