### ISSUE TITLE
[Feature request]: Need Ability to prevent multiple Open Shifts for same Cashier (using Role Permission)

### ISSUE THREAD

**Issue by bkm888** [yrestom/POS-Awesome#155]
### Is your feature request related to a problem? Please describe.

Current problem is if a user opens 2 shifts and has sales in both shifts, then only closes one of the shifts. The shift that remains open will not be able to be closed the following day. The error generated is one regarding a closed shift already existing in same time period.

### Describe the solution you'd like

Would like the ability to remove the ability in the Role permissions for the Sales User to "Create" Opening Shifts and yet still have the POS Awesome App startup force an Open Shift without needing the permission.

Yousef, you an I worked on this over the phone today and you wanted me to open this request to remind you about it.

You evidently had to make changes to both ERPnext code and POS Awesome code on the sandbox server we were testing in order to get this to work properly.

Hope this helps.

BKM

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/985a1932128d3a671f0526b02c3837125bdda2e2
