### ISSUE TITLE
[BUG]:  Discount Limit not working

### ISSUE THREAD

**Issue by NickRott** [yrestom/POS-Awesome#157]
### Versions
{
	"chat": "0.0.1",
	"contract_payment": "0.0.1",
	"ecommerce_integrations": "1.9.1",
	"erpnext": "13.29.0",
	"erpnext_shipping": "0.0.1",
	"erpnext_telegram_integration": "1.0.1",
	"frappe": "13.29.0",
	"posawesome": "3.2.2",
	"project_payroll": "0.0.1",
	"twilio_integration": "0.0.1",
	"whitelabel": "0.0.1"
}
![Screenshot (788)](https://user-images.githubusercontent.com/105024269/168490299-80caa571-cc56-41ff-912f-91a3d804c4b0.png)

### Steps to reproduce
![Screenshot (789)](https://user-images.githu
![Screenshot (790)](https://user-images.githubusercontent.com/105024269/168490291-20b730da-6764-453c-a2f3-eb317fdaa14e.png)
busercontent.com/105024269/168490286-4155bf92-18c5-4838-b988-69cd8313e7b4.png)

![Screenshot (785)](https://user-images.githubusercontent.com/105024269/168490278-1bde9022-3e63-4ae1-841d-9d2ea99dff75.png)

1.  Set Max Discount Percentage Allowed in POS Profile
2.  Select Allow User to Edit Item Discount
3.  Cashier is allowed to set any level of discount in POS

![Screenshot (792)_LI](https://user-images.githubusercontent.com/105024269/168490448-554f39be-9c89-485b-95af-fc6816d455b0.jpg)

**Comment by yrestom** [comment]
It is not a bug, but it applies max_discount field from item master

**Comment by N1RMS** [comment]
where can i find this field?

**Comment by N1RMS** [comment]
Found it. It was on a different perm level
