### ISSUE TITLE
[BUG]: POS Awesome Workspace not found in V14 beta

### ISSUE THREAD

**Issue by AlaaBadry** [yrestom/POS-Awesome#158]
<!--  Thanks for your time to make POS Awesome better with your feedback 👍

**IMPORTANT** Before reporting a bug:

A properly detailed bug report can save a LOT of time and help fixing issues as soon as possible.
- ->

### Versions

- Frappe: 14 beta
- Erpnext: 14 beta
- POS Awesome: 3.2.2

### Stacktrace / full error message

```javascript
(paste here)
```

### Steps to reproduce

workspace not found

**Comment by yrestom** [comment]
POS Awesome does not support V14 yet and will start working on that after the stable release comes out

**Comment by muchai** [comment]
Related. I see POS Awesome is available for installation on develop branch, but there's no sidebar menu for POS Awesome once it's installed on develop branch.

**Comment by blewsky** [comment]
Please also publish on market place for Version 14.  Thank you
Version 14 has been out since several weeks and we would like to migrate to V14 as soon as our installed apps are supported on V14.

**Comment by karanwilson** [comment]
> I haven't started working on supporting version 14 yet, I think I will start working on that in October

Dear Yousef Restom,
Would you be releasing a version compatible with ERPNext version-14 this month?

**Comment by karanwilson** [comment]
Dear @yrestom ,
Requesting an approximation by when you would be working on the POS-Awesome version for ERPNext-14

**Comment by yasser1248** [comment]
> Dear Yousef Restom,
we are waiting for releasing a version compatible with ERPNext version-14
thanks in advance

**Comment by yrestom** [comment]
I started working on it and you can find it at this [branch](https://github.com/yrestom/POS-Awesome/tree/version-14) 
Please note that it needs to be tested and it is not yet ready for production
