### ISSUE TITLE
UI not working in Safari

### ISSUE THREAD

**Issue by EddieDee** [yrestom/POS-Awesome#16]
I noticed the UI is not working properly, found out the assets/js/awesomplete.min.js.map is not loading 404, could it be it? nevertheless it works on Chrome
<img width="1280" alt="Screen Shot 2020-11-23 at 1 15 50 AM" src="https://user-images.githubusercontent.com/79041/99931079-a5975700-2d29-11eb-9e49-8848397b6e2e.png">

**Comment by yrestom** [comment]
It's weird, it's been tested on Safari, and it works just fine.
Make sure that you are properly installing the app and that your browser is up to date.
