### ISSUE TITLE
[BUG]: Currencies with 3 decimal places causing issue with payment amount

### ISSUE THREAD

**Issue by hahayusuf** [yrestom/POS-Awesome#160]
### Versions

ERPNext: v13.23.0 (version-13)
Frappe Framework: v13.23.0 (version-13)
POS Awesome: v3.2.1 (master)

### Steps to reproduce

1. Go to 'POSAwesome'
2. Add item with price including a three decimal place price such as: 5.634
3. Click pay
4. Select payment method as credit card
5. Click submit payments
6. See error from POSAwesome: "The amount paid is not complete"

### What is Expected?
Payment should be registered in POSAwesome

### What is actually happening?
Error shown because amount to be paid is rounded down to two decimal places.

The item price uses three decimal places as defined in the accounting app. Not sure why POSAwesome does not pick this up.

Could not find a place price decimal place can be configured in POSAwesome.

**Comment by hahayusuf** [comment]
Hello again

I have taken the time to explore the code and it seems that the `toFixed(2)` is used in multiple instances.

One of the places it is used is this function:

```
formtCurrency(value) {
      value = parseFloat(value);
      return value.toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,');
}
```

It would be nice to be able to configure it to 3 globally without having to change the code.

That will allow POSAwesome to be used for all currencies. According to the following list, a total of eight currencies use 3 decimal places: [https://docs.adyen.com/development-resources/currency-codes](https://docs.adyen.com/development-resources/currency-codes)

I can see how this was easily overlooked as a required because the vast majority of currencies only require 2 decimal places.

**Comment by yrestom** [comment]
It is related to this issue https://github.com/yrestom/POS-Awesome/issues/106
And it should be fixed with this commit https://github.com/yrestom/POS-Awesome/commit/f3462da84a05c0323bb9551e6de872f29c73f691
It is available now on develop branch

**Comment by hahayusuf** [comment]
Many thanks for your quick response!
