### ISSUE TITLE
[BUG]: Price ruling is not being applied on the product in POS Awesome

### ISSUE THREAD

**Issue by yangansheng** [yrestom/POS-Awesome#166]
### Versions
ERPNext: v13.31.1 (version-13)
Frappe Framework: v13.30.0 (version-13)
POS Awesome: v3.3.0 (master)

I have a price rule for a product that states that 1pk sells PHP7.00 but if the customer will buy 10 or more pks each pk will costs 5.60. This price rule works when using the ERPNEXT POS but not when using the POS Awesome. All other price rules for the other products do not work as well. See the images below

ERPNEXT POS
![image](https://user-images.githubusercontent.com/7309461/171649358-b34f42e2-422a-4977-b32c-ea43a4654c3e.png)

POS AWESOME
![image](https://user-images.githubusercontent.com/7309461/171650521-1d769eb8-2fde-4e86-acf4-202d50980a4c.png)

**Comment by yrestom** [comment]
POS Awesome is not supporting pricing rules instead it's using [POS Offers](https://github.com/yrestom/POS-Awesome/wiki/Promotions-and-Offers)
