### ISSUE TITLE
[Feature request]: Request for a 'Receipt Printing' prompt

### ISSUE THREAD

**Issue by Freshdigits** [yrestom/POS-Awesome#167]
### Is your feature request related to a problem? Please describe.

One humble request to implement a prompt for 'Receipt Printing' just like the native Retail POS in ERPNext after clicking the payment button. curretly POS Awesome doesn't have this feature and it's creating a little frustration. infact, not all customers needs the pos receipt and we are printing the bill for each and every transactions. so if we implement this feature we can give the bill only for those customers who really needs it. A screenshot from the native ERPNext Retail POS  has been added below for a better explanation. 

thank you so much for the wonderful product POS Awesome.

![Screenshot from 2022-05-24 17-18-42](https://user-images.githubusercontent.com/6417545/172024746-1440d93f-ce82-4aa9-9fe6-dc1b37d34535.png)

**Comment by tedyswaga** [comment]
on the browser print dialogue just click cancel
