### ISSUE TITLE
Custom script?

### ISSUE THREAD

**Issue by EddieDee** [yrestom/POS-Awesome#17]
Is there a way to integrate custom scripts? We use some script for sales invoice that are not integrated with this new POS, will it require to do it on VUEjs inside the app?

**Comment by yrestom** [comment]
Yes, the code must be modified directly from the app.

**Comment by EddieDee** [comment]
What do you recommend to be able to separate concerns? maybe a different branch or is it other way to include from an external file?

**Comment by yrestom** [comment]
Can you give me more details

**Comment by EddieDee** [comment]
Thanks!

So right now we use a custom script under sales invoice for:
 1. We automatically generate a new client if the tax id is not in our system but present in a external document produced by the goverment.
 2. We use different naming series for the invoice depending on the type of client.
 2. We also use a different naming series ( require by government) depending on the type of client.

**Comment by yrestom** [comment]
I understand 
I think is the best way to do this is making those changes directly to the code by forking the project

**Comment by EddieDee** [comment]
thanks!
