### ISSUE TITLE
[BUG]: POS Offer not applying or showing in POS Awesome

### ISSUE THREAD

**Issue by yangansheng** [yrestom/POS-Awesome#170]
ERPNext: v13.32.0 (version-13)
Frappe Framework: v13.31.0 (version-13)
POS Awesome: v3.3.0 (master)

 have a rule setup like this in POS Offer (example given here is for item DP03 2x3).
![image](https://user-images.githubusercontent.com/7309461/172521197-646599c1-0afd-441d-873b-a3953e75e457.png)
![image](https://user-images.githubusercontent.com/7309461/172521330-5e8b1706-03ed-44a4-838f-2446c0296346.png)

I also configured my POS Profile to ignore price rule
![image](https://user-images.githubusercontent.com/7309461/172521273-1c7d04bc-274a-4503-91f9-781728e93342.png)

But still the rule does not apply
![image](https://user-images.githubusercontent.com/7309461/172520940-1e6a5720-a038-4ff7-8418-e2ba7001e8d7.png)

**Comment by yrestom** [comment]
Mostly there is something wrong in the setup of the offer or you just need to refresh the browser
