### ISSUE TITLE
[Feature request]: Allow setting of default values for Customer Group and Territory when creating new customer

### ISSUE THREAD

**Issue by lxnow** [yrestom/POS-Awesome#171]
When creating a new customer, it is typically part of a group (e.g. "Individual") and territory. It would be more efficient to have this field pre-populated based on a default value set in POS Profile -> POS Awesome settings.
![image](https://user-images.githubusercontent.com/5035210/172605832-f82f474a-f29e-4cae-ad60-73ca1005bb7c.png)

**Comment by elan-k** [comment]
The default value on the profile is the most helpful feature for customer group & territory.
