### ISSUE TITLE
[BUG]: Change in UOM is not recognized

### ISSUE THREAD

**Issue by yangansheng** [yrestom/POS-Awesome#172]
ERPNext: v13.32.0 (version-13)
Frappe Framework: v13.31.0 (version-13)
POS Awesome: v3.3.0 (master)

Setup: 1 pack (pk) of the item sells PHP7. 10 packs or more, each would then costs 5.60. This works without a problem but if I changed the UOM to a bundle (in this case one bundle has 20 packs), it just shows that I'm selling 1 pack. 
![image](https://user-images.githubusercontent.com/7309461/172756144-a9ea991e-12f4-4361-a78b-cf8be6f532f7.png)

**Comment by yrestom** [comment]
That’s correct, because it will reflect on Stock QTY as in your image, you can see it shows 20 which is correct
Please complete this transaction and checkout the stock ledger

**Comment by yrestom** [comment]
I think this issue is because of an incorrect Item Price setup
So you have two options:
1.  Set a specific price for each UOM
2. Remove the UOM from the item price

Regards
