### ISSUE TITLE
[BUG]: POS Offer- Give Product with 0 Rate or 100% disc error

### ISSUE THREAD

**Issue by bobzz-zone** [yrestom/POS-Awesome#177]
Versions

- Frappe: 13.32.0
- Erpnext: 13.33.0
- POS Awesome: 3.3.0

Steps to reproduce

1. Create POS Offer by item code , and give product type , set rate 0 for the given product
2.  Create order on POS
3.  Apply POS Offer
4.  Offer Added as expected
5. Make Payment
6. check the sales invoice , and offered product is missing

What is Expected?
Expected offered product should be added

What is actually happening?
Offered product is missing

Additional context
its also happends with 100% discount 

Screenshots
![image](https://user-images.githubusercontent.com/1543515/174699804-22ec363c-52f2-4cf7-a963-be0237ad4a8e.png)
See Screenshot.. missing row 1

**Comment by yrestom** [comment]
I tried to reproduce the issue and it seems to work fine so can you provide more details?

**Comment by 1475963elyus** [comment]
https://user-images.githubusercontent.com/110019678/180953189-7697d46b-e1bb-4715-80f9-56922d84b32a.mp4

free items (from buy 1 get 1 promo ) don't appear when printed

**Comment by yrestom** [comment]
Hi @1475963elyus 
I think this issue is related to the print format you are using

**Comment by 1475963elyus** [comment]
Hi, sir
how to set up the print format, so then the free item can appear.. ?

thanks
Melyus

Pada tanggal Sel, 26 Jul 2022 pukul 15.43 Yousef Restom <
***@***.***> menulis:

**Comment by yrestom** [comment]
The issue from this line in Erpnext
```
if not pricing_rules:
	remove_free_item(doc)
```	
https://github.com/frappe/erpnext/blob/69087b8790d0b17f17c8755ec2d31d57374813ae/erpnext/accounts/doctype/pricing_rule/utils.py#L545
