### ISSUE TITLE
Salex Tax by item or Item group not calculating

### ISSUE THREAD

**Issue by Maree27** [yrestom/POS-Awesome#179]
Pos Awesome is not calculating item tax or item group tax accordingly.

For example:

If we set sales tax of 25% for item A and 5% for item B so it should take the tax accordingly but right now system is not calculating correctly. Its taking the sales tax of first item whatever it is  and make exactly the same for the second item.

Same if we put sales tax to item group its also giving the same problem using POS Awesome.
But by default in ERPNext its working fine.

**Comment by yrestom** [comment]
@Maree27 
Can you share please which versions you are using for Frappe, Erpnext, POS Awesome

**Comment by Maree27** [comment]
Version 14 now and latest posawesome version for 14
