### ISSUE TITLE
Cash payment method issues

### ISSUE THREAD

**Issue by Ismail2929** [yrestom/POS-Awesome#18]
Hi, im facing issue whenever i do pos closing my cash always been more in expected amount. But my grand total is exactly the same with my real total cash + debit. Picture as below, can see that expected amount is more than transaction that have been registered.
![Screenshot_2020-11-26 POSA-CS-20-0000002](https://user-images.githubusercontent.com/70574326/100258705-539d3e00-2f82-11eb-9f69-3075cf422258.png)

**Comment by yrestom** [comment]
Wich Erpnext & Frappe & POS Awesome version do you have and if have any customization it will affect this?

**Comment by Ismail2929** [comment]
ERPNext: v12.14.0 (version-12)

Frappe Framework: v12.12.0 (version-12)

POS Awesome: v1.0.0 (master)

currently my version as above and no any customization that have been made for it.

**Comment by yrestom** [comment]
I could not repeat the problem, and it did not appear on any of the sites that I have

**Comment by Ismail2929** [comment]
okay i will check again from my site what the cause of the problem. Thank you for your help.

**Comment by Ismail2929** [comment]
Hi,

for this issue i already found the cause of the problem. It seems that cash expected amount are taken from amount that have been paid by customer. Example price is $6 but customer paid $10 change amount will be $4. In expected amount it will take $10 but supposedly it will take $6. Example picture as below:

![Screenshot_2020-11-30 New POS Closing Shift 2](https://user-images.githubusercontent.com/70574326/100570938-dd476580-330c-11eb-897d-9a07ae18c7ea.png)
![Screenshot_2020-11-30 SG CHUA - INV2011-0880](https://user-images.githubusercontent.com/70574326/100570944-df112900-330c-11eb-9409-a55df5fd9ddf.png)

**Comment by Botanium** [comment]
I will try to replicate this and give you feedback if I can reproduce it.

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/6bf5fac157055cd3ee7089bf5a7f4e2dd36d0b83
