### ISSUE TITLE
POS Opening Shift doctype field “amended_from” duplicated

### ISSUE THREAD

**Issue by Rafabelong** [yrestom/POS-Awesome#189]
I tried to add a custom field on the POS Opening Shift doctype for POS AWESOME.
But I couldn´t, because a mensage said “duplicated field at rows…” (row 16 and 17)
And that is true, the last 2 rows “amended_from” are duplicated by default. I checked out others instances with oldes vertions and all are equal.
I am not depelover and I can´t understand how it is posible as I belive every var should be unique on a doctype.
My question is, if are there any reason what I don´t undertand for that and if can I delete the duplicated row without cause any problem later?
Fallowing is the document fields table by default as it is look like:

LABEL                      FIELD TYPE      VAR NAME
1 Period Start Date Date Time period_start_date
2 Period End Date Date period_end_date
3 Status Select status
4 Colum Break column_break_3
5 Posting Date Date posting_date
6 Set Posting Date Check set_posting_date
7 Section Break section_break_5
8 Company Link company
9 POS Profile Link pos_profile
10 POS Closing Shift Date pos_closing_shift
11 Column Break column_break_7
12 Cashier Link user
13 Section Break
opening_balance_details_section
14 Opening Balance Details Tab balance_details
15 Section Break section_break_9
16 Amended From Link amended_from
17 Amended From Link amended_from

Both duplicated fields are linked to the same doctype POS Opening Shift.

Thank you in advance

**Comment by elan-k** [comment]
Looks like it's not resolved yet.. 
[https://github.com/yrestom/POS-Awesome/issues/141](https://github.com/yrestom/POS-Awesome/issues/141)
