### ISSUE TITLE
Weighted Scaled item feature doesn't work.

### ISSUE THREAD

**Issue by Botanium** [yrestom/POS-Awesome#19]
I have tried to use a weighted scale device to get the value from the electronic scale, but there isn't any integration implemented.

**Comment by yrestom** [comment]
Unfortunately, it doesn't work that way, you should use a barcode for that

**Comment by Botanium** [comment]
Can you elaborate a little more? I don't get the workflow. Should I let the scale to generate the barcode? and then scan it on the POS Awesome?

**Comment by yrestom** [comment]
Yes, let the scale generate the code. However, make sure that in the PoS Profile you have set the proper starting digits for scale items. "Scale Barcode Start With" field

**Comment by Botanium** [comment]
Where is the code located for parsing the barcode? I still don't know how this works exactly.

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/blob/ff338e362507bdde53f6ec35575c51da94741c3c/posawesome/public/js/posapp/components/pos/ItemsSelector.vue#L235

**Comment by bobzz-zone** [comment]
@yrestom just wanna confirm.. the formats is "{scale_marking_3_digits}{item_barcode}{weight}" ?

**Comment by yrestom** [comment]
Yes it is correct

**Comment by dawoodjee** [comment]
> @yrestom just wanna confirm.. the formats is "{scale_marking_3_digits}{item_barcode}{weight}" ?

Hey @yrestom did you get your weighted items to work?

Kindly show a screenshot of starting with value and Item barcode, if possible even a successful scan

@duncan-nkhata and I have been testing for a week but cant get this to work

Now I'm reviewing the code to try and make sense of things

**Comment by dawoodjee** [comment]
Resolved

The catch is to only add the first 7 digits of your barcode to the item like so
![image](https://user-images.githubusercontent.com/7912989/106320598-c2955c80-627b-11eb-8397-93ede3971413.png)

POS Profile starts with 
![image](https://user-images.githubusercontent.com/7912989/106320711-ea84c000-627b-11eb-95c8-c0f16be2f943.png)

This works fine
![POSAWESOME](https://user-images.githubusercontent.com/7912989/106320761-fc666300-627b-11eb-94e7-9c7ae5874727.gif)
