### ISSUE TITLE
Sales Tax exempt

### ISSUE THREAD

**Issue by dnyt84** [yrestom/POS-Awesome#193]
I have customers that are sales tax exempt.
I have set that option in their profile. 
When I pull up the customer in POS-Awesome and select the items and click on PAY sales tax is still charged to the customer.

Is there any way to enable Sales TAX exempt sales?

Thank you

Daniel

**Comment by dnyt84** [comment]
Running following versions:
ERPNext: v13.36.5 (version-13)
Frappe Framework: v13.39.0 (version-13)
POS Awesome: v3.4.0 (master)

**Comment by yrestom** [comment]
@dnyt84 
If you are using taxes rules it will not work because it's not supported

**Comment by dnyt84** [comment]
should we not honor the sales tax exempt status when we select a customer in the drop down though?

**Comment by N1RMS** [comment]
I had a related question. Will POS Awesome allow sales tax exempt items to be sold? For eg, One item group of products is exempt from tax. How can i make sure to not charge the customer for this?

**Comment by Rafabelong** [comment]
> 

Hi NIRMS. 
To avoid add tax value on an item o for a whole iteam group you can:
1. Create an Item Tax Template with all the same tax accounts present in the Sale Invoce Tax Template used in the Pos Profile and set on each  % Value = 0 
2. Set this Item Tax Template on the item master or the Item Group master as needed.
I know the concept Tax Exception technically is not the same than Tax % = 0 but the result is similar and works for me.
Regards
