### ISSUE TITLE
Product Bundles not validating availability properly

### ISSUE THREAD

**Issue by olamide2** [yrestom/POS-Awesome#20]
All Product bundles are showing as zero quantity (which is right) but PoS Awesome is validating them as not available so not allowing us complete the transaction when negative quantity is not allowed

**Comment by olamide2** [comment]
Hi 

any upate on this?

**Comment by Botanium** [comment]
I am heavily dependent on Product bundles. I will test that and see if I am getting the same error so I can confirm it.

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/c1a8a8b882b61b623aacb105ac85ba2216cbb0c4
