### ISSUE TITLE
[BUG]: Redemtion of Loyalty Points 

### ISSUE THREAD

**Issue by AliDevel** [yrestom/POS-Awesome#200]
### Versions

- Frappe: 
- Erpnext: 
- POS Awesome: 3.4.0

What is Actually happening?
Redemption of loyalty points doesn't work. However it works in core POS. 
When you add Redemption points, it adds assigns to Paid Change and adds to Paid amount Sum. 

What is Expected?
To reduce Redemption amount from Paid amount.

![Screenshot 2022-09-24 112658](https://user-images.githubusercontent.com/94564048/192090759-0ade9b0a-6dae-45f6-ad80-ec99aa22bd21.png)

**Comment by yrestom** [comment]
@AliDevel the user should change the paid amount from the other payments method manually
