### ISSUE TITLE
Batch no data available

### ISSUE THREAD

**Issue by Ismail2929** [yrestom/POS-Awesome#21]
Hi, im having issue with item batch no. It shows no data available at batch no. im using ERPNext: v12.14.0 (version-12), Frappe Framework: v12.12.0 (version-12) and POS Awesome: v1.0.0 (master).
![Capture1](https://user-images.githubusercontent.com/70574326/100537729-de718780-3265-11eb-9f42-18abf5b29f24.PNG)
![Capture2](https://user-images.githubusercontent.com/70574326/100537733-e03b4b00-3265-11eb-99a1-6627486d19d2.PNG)
![Capture3](https://user-images.githubusercontent.com/70574326/100537735-e16c7800-3265-11eb-8d06-765bb7141e7f.PNG)

**Comment by yrestom** [comment]
Check if those batches exist in the same warehouse you are using in pos profile

**Comment by Ismail2929** [comment]
As per check yes, the batches exist in the same warehouse with the pos profile. The qty show correctly but cannot read the batch number.

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/e9b9ebd5b0650c7da3db6ceddb3126fa70dc1ced
