### ISSUE TITLE
unable to update site after uninstall of posawesome

### ISSUE THREAD

**Issue by sahilsinghania** [yrestom/POS-Awesome#211]
After i uninstalled pos awesome was unable to acess sales invoice as doc type pos offer was not there now i have deleted the sales invoice link to pos affer so it is fixed but now unable to update website getting error

"frappe.core.doctype.doctype.doctype.WrongOptionsDoctypeLinkError: Address: Options must be a valid DocType for field Delivery Charges in row 21"

please help me resolve it

**Comment by yrestom** [comment]
@sahilsinghania I am not sure if it is related to POS

**Comment by blewsky** [comment]
Similar problem after uninstalling POS-Awesome and migrating to V15 of Frappe/ERPnext:
"Missing DocType
Field posa_delivery_charges is referring to non-existing doctype Delivery Charges. Please delete the field from [Sales Invoice-posa_delivery_charges](https://flamingoofoods.frappe.cloud/app/custom-field/Sales%20Invoice-posa_delivery_charges) or add the required doctype."

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/d7acc8d9b59e091f4422de09870ca449e08ae302
