### ISSUE TITLE
[BUG]: Not able to print if cart has more than 20 items, doesnt open the print dialogue but saves the trandaction

### ISSUE THREAD

**Issue by tedyswaga** [yrestom/POS-Awesome#213]
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

**Comment by yrestom** [comment]
@tedyswaga 
I am not able to reproduce the error
Can you please share more info about how we can recreate that error?

**Comment by tedyswaga** [comment]
Sorry, the browser somehow was blocking pop ups for receipts printing.
