### ISSUE TITLE
[BUG]: Insufficient Permission for POS Payment Method , this error shows when I run app

### ISSUE THREAD

**Issue by thecoder066** [yrestom/POS-Awesome#222]
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

**Comment by mrmikey05** [comment]
Same here. Went into User->Role Permission Manager->Mode of Payment and added System User to no luck as well. Prior to this change, I created a warehouse, create customer, add some items, create pos profile and then start POS Awesome on a fresh install, fresh site. Dismissing this popup result in nothing showing up on the list of Company and POS Profile. I attach a photo for reference as OP didn't supply one. I hope this work out soon as I am looking forward to put this together for a project.
![Insufficient Permission Mode of Payment Popup](https://user-images.githubusercontent.com/13059250/207217089-897cdca3-36c4-4d27-b965-cb015f6527bd.png)
![Empty Company](https://user-images.githubusercontent.com/13059250/207217104-bf88a2ed-5928-4cf4-a10b-f046f6d4b08e.png)
![Empty POS Profile](https://user-images.githubusercontent.com/13059250/207217110-b4e79dd1-3fff-4c17-aa59-115e0d4ff1d9.png)

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/pull/223
