### ISSUE TITLE
[BUG]: Partial Payment Invoice getting recorded as 'Paid' with 'outstanding amount' as 0

### ISSUE THREAD

**Issue by karanwilson** [yrestom/POS-Awesome#226]
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

### Steps to reproduce

1. Go to 'POS Awesome'
2. Select Customer, and Items for purchase, and click on Pay.
3. Input part payment through 'redeem customer credit', and Click on 'Submit Payment'.
4. Check Invoice list, to see Invoice marked as 'Paid'
5. Check Payment Entry list, to see that the 'Part Payment' amount and 'Outstanding' amount are getting submitted as two 'Payment Entry'

### What is Expected?
Invoice should be recorded as 'Partly Paid', and no 'Payment Entry' should be recorded.

### What is actually happening?
Invoice is getting recorded as 'Paid' ; and the 'Part Payment' amount and 'Outstanding' amount are getting submitted as two 'Payment Entry'

### Screenshots

![Screenshot from 2022-12-17 12-09-29](https://user-images.githubusercontent.com/48678570/208230145-90d267e2-3c78-47b7-a2c1-e7192eeaf685.png)

![Screenshot from 2022-12-17 12-10-16](https://user-images.githubusercontent.com/48678570/208230167-ae218c3f-3280-4cc2-ad7b-736cdb5f5eb0.png)

![Screenshot from 2022-12-17 12-12-19](https://user-images.githubusercontent.com/48678570/208230180-c8b8a9c2-502d-4b2c-b97a-b83fc59e50ff.png)

![Screenshot from 2022-12-17 12-11-09](https://user-images.githubusercontent.com/48678570/208230186-34ece84f-50a8-432b-9eef-73401d1bb7d1.png)

![Screenshot from 2022-12-17 15-36-46](https://user-images.githubusercontent.com/48678570/208236709-f6986d39-b418-4e15-a8f1-81c2f4cc11a3.png)

**Comment by yrestom** [comment]
Please write the installed Apps versions

**Comment by karanwilson** [comment]
Dear @yrestom , sorry for missing that information:-
ERPNext: v13.42.2
Frappe Framework: v13.45.1
POS Awesome: v3.4.1 branch: version-13

**Comment by yrestom** [comment]
I thinks it is related to https://github.com/yrestom/POS-Awesome/issues/127

**Comment by karanwilson** [comment]
Dear @yrestom 
I tested the partial payment issue after applying the above mentioned "redeem loyalty points" fix, but the issue still remains..
Request your advice

**Comment by yrestom** [comment]
@karanwilson 
Please contact me on Telegram

**Comment by karanwilson** [comment]
Dear @yrestom 

I found the fix for our specific scenario, where we have no cash transactions - only advance payments and credit sales - the credit sales are then paid by the customer as an extra payment at the end of the month.

Hence in the exception case of partial payments, the balance amount is not paid in cash, but is recorded as a 'credit sale'.

[fix: factored in 'To Be Paid' amount in 'submit_invoice'](https://github.com/yrestom/POS-Awesome/commit/05f46c769450d0b1ffd794140dcfab176fc158bd)

**Comment by karanwilson** [comment]
> 

Requesting your Telegram username

**Comment by karanwilson** [comment]
> @karanwilson Please contact me on Telegram

Requesting your Telegram username
