### ISSUE TITLE
[BUG]: POS Return is not working

### ISSUE THREAD

**Issue by thida-bcn** [yrestom/POS-Awesome#227]
when I create return invoice i got message
Paid amount + Write Off Amount can not be greater than Grand Total
ERPNext: v13.41.1 (version-13)
Frappe Framework: v13.43.2 (version-13)
Awesome: 3.4.1

**Comment by yrestom** [comment]
Can you share the error from the console?

**Comment by thida-bcn** [comment]
[image: image.png]
i don't have console log
[image: image.png]
no error log as well
[image: image.png]
i can give you url, id and pwd
Thanks and Regards,
Thida
Business Development Director

Business Centric Network Company Limited
+959 977 160 671
+959 254 677 192
***@***.***
https://businesscentricnetwork.com/

**Comment by yrestom** [comment]
@thida-bcn Unfortunately, the pictures did not appear

**Comment by yrestom** [comment]
@thida-bcn 
Unfortunately, these images are not useful, I need the error that appears in the console of the browser

**Comment by thida-bcn** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/62122640/209295212-cac5aafc-295c-4aa0-aa97-e9356e55121e.png">

**Comment by yrestom** [comment]
This should be fixed here https://github.com/yrestom/POS-Awesome/commit/4ecaf4a85b6da5a8a3894e8d1910d16b76d05597

Make sure your app is updated and do bench restart
