### ISSUE TITLE
[Bug] Printing Receipts only shows {{body}}

### ISSUE THREAD

**Issue by Botanium** [yrestom/POS-Awesome#23]
if you select any item and after the payment, when you press the print, it opens a new window and shows {{body}} only at the top left corner of the screen.

**Comment by yrestom** [comment]
Go to pos profile, select the print format, if your print format is blank, and also check your pos profile if the Naming Series is correct

**Comment by Botanium** [comment]
There was an error and my friend fixed it, I will tell her to make a PR.

**Comment by yrestom** [comment]
Please review this :
https://discuss.erpnext.com/t/print-preview-error-body/49015/11

**Comment by Botanium** [comment]
I have reviewed it and it is very valid. My friend was able to fix it by changing this code. I think during the concatenation of this happened. I will create a PR and please review. 
<img width="892" alt="Screen Shot 2020-12-07 at 9 18 59 AM" src="https://user-images.githubusercontent.com/3994826/101316501-a376e180-386d-11eb-8b1e-d46ce4d2b98b.png">
