### ISSUE TITLE
[BUG]: Permission of Customer Creation

### ISSUE THREAD

**Issue by saud-2** [yrestom/POS-Awesome#232]
**Any user who has access to the POS-Awesome can create a customer even if he does not have the permission to create a customer .**

- Frappe: v14.20.0 (version-14)
- Erpnext: v14.11.0 (version-14)
- POS Awesome: v4.1.0 (develop)

**Comment by yrestom** [comment]
It's intended behaviour, but if there is a use case you can explain it

**Comment by saud-2** [comment]
the best practice and control is to have one account for a customer especially when you deal with hem by credit and have credit limit should not be exceed it. to achieve this and to avoid duplicate accounts ,restrict creation of account to specific users.

**Comment by yrestom** [comment]
I agree with you, please create a new feature request from [here](https://github.com/yrestom/POS-Awesome/issues/new?assignees=&labels=&template=feature_request.md&title=%5BFeature+request%5D%3A+)
