### ISSUE TITLE
[BUG]: I have a problem with the exchange amount process

### ISSUE THREAD

**Issue by MTAS101** [yrestom/POS-Awesome#235]
hi
I have a problem with the exchange amount process
The customer has a $32 bill and $100 payment
The amount returned to the customer is $32 through the employee
The shift closed the accounts correctly
But in the general ledger, the amounts are incorrect and the full amount is $100. The exchange was not deducted to the customer
There should be $32 
![Untitled-1](https://user-images.githubusercontent.com/70178281/209993689-a0d37ab9-5de3-459c-95f5-2729f7e5f041.png)
![Untitled-2](https://user-images.githubusercontent.com/70178281/209993694-7ee8b5db-56e9-409b-9c44-8c0fcd6eb6d3.png)
![Untitled-4](https://user-images.githubusercontent.com/70178281/209993695-481dde45-d588-427c-a9aa-83beef90f314.png)
in the general ledger as it is in the shift closing
Please see the attachments

Thanks

**Comment by olamide2** [comment]
Hi, go and check the change account you chose in the PoS Profile, normally the change account should be the same as the account for the cash Mode of payment. T

he system will have credited the change amount to the change account nominated in the Pos Profile
