### ISSUE TITLE
POS User able to open shift for profile not assigned

### ISSUE THREAD

**Issue by tedyswaga** [yrestom/POS-Awesome#237]
I have different users for different pos profiles, but getting situations where a user is able to login to open shift with any pos profile including which they are not assigned to

**Comment by yrestom** [comment]
You can use User Permission to control that

**Comment by tedyswaga** [comment]
user permission works fine..but if u have alot of users it will be a bit cumbersome

**Comment by yrestom** [comment]
@tedyswaga You are right
Can you please add it as a feature request
