### ISSUE TITLE
[BUG]: Inputing item discount percentage leads to wrong discount amount

### ISSUE THREAD

**Issue by rvbd** [yrestom/POS-Awesome#243]
Hi, been testing this locally and has so far found this blocker issue. I'm not sure if it's configuration or an actual bug. If I looked at the code it looks right in the calc function, but I'm not a vue developer so can't say for sure.

So the way to reproduce:
1. Open POS Awesome app
2. Select an item
3. Enter discount percentage
4. Look at the discount amount, currently not the correct amount. In the screenshot below I'm trying 10% discount.
![image](https://user-images.githubusercontent.com/1558550/213640223-93955fac-ceef-405e-9a40-1e3bd71bd4c4.png)

Thanks a lot.

**Comment by yrestom** [comment]
What APPs version you have in you site ?

**Comment by rvbd** [comment]
Hello, I used the version v4.1.0 master
