### ISSUE TITLE
[BUG]: Referral Company is causing issues with multi company setup

### ISSUE THREAD

**Issue by mujeerhashmi** [yrestom/POS-Awesome#244]
- Erpnext: 
- POS Awesome: 

### What is Expected?
I am not sure if a referral company is a must. If it is not then we can avoid using it in the customer doctype.

### What is actually happening?
In a multi-company setup, we would want the customer doctype to be accessible to employees across the companies. But with the referral company field in the customer doctype being populated it hampers the intended functionality. We set user permissions for the company field with is_default checked for employees belonging to different companies and this populates the company field in customer doctype.

Our Setup:
Global Default: Company1
Company1 User: Creates patients and the linked customer doctype is created with referral company as Company1. He has user permission for Company1 and is_default is checked.
Company2 User: Wants to bill medicines but cannot access customer created before because he has permissions set for Company2 and is_default is checked.

We are getting this exception [here](https://github.com/frappe/erpnext/blob/f6f64083d2252b4f818650270f0d0e41e89d3f84/erpnext/accounts/party.py#L108)

**Comment by yrestom** [comment]
A quick fix, you can change that field to a data field

**Comment by mujeerhashmi** [comment]
Thank you very much for the response. I could not manage to change it though through customize.

**Comment by yrestom** [comment]
Please try to change it from Property Setter or you can delete it and create Data field with same name
