### ISSUE TITLE
[BUG]: Server message shown after submit payment

### ISSUE THREAD

**Issue by abdo-host** [yrestom/POS-Awesome#245]
### Versions

- Frappe: 13.46.2
- Erpnext: 13.42.5
- POS Awesome: 3.5.0

### Stacktrace / full error message

when I submit payment, server message shown with 0.0 value

`_server_messages: "[\"{\\\"message\\\": \\\"0.0\\\", \\\"title\\\": \\\"Message\\\"}\"]"`

#### Screenshot

https://nimb.ws/QbzR9Z

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/e58add77a8ec447b10767eb43b21c684ce15b0d3
