### ISSUE TITLE
[BUG]: posawesome.posawesome.api.posapp.get_item_detail

### ISSUE THREAD

**Issue by xTrikuta** [yrestom/POS-Awesome#246]
POS Awesome Give error after bench update --reset

Failed to get method for command posawesome.posawesome.api.posapp.get_item_detail with cannot import name 'payment_app_import_guard' from 'erpnext.utilities' (/home/xtrikuta/frappe-bench/apps/erpnext/erpnext/utilities/__init__.py)

![image](https://user-images.githubusercontent.com/96610603/214513565-b85204a1-c5be-41fe-a014-98ca3cb4b207.png)

- ->
ERPNext: v14.13.0 (version-14)
Frappe Framework: v14.23.0 (version-14)
Payments: v0.0.1 (develop)
POS Awesome: v4.1.1 (develop)

**Comment by elan-k** [comment]
Check this issue, 

https://github.com/yrestom/POS-Awesome/issues/260

Hope it is relevant!

**Comment by yrestom** [comment]
@xTrikuta Please use version-14 branch instead of develop branch with Erpnext V14
