### ISSUE TITLE
Duplicate key price list

### ISSUE THREAD

**Issue by lstbrian** [yrestom/POS-Awesome#252]
Not sure if this is normal during installation on docker windows 10?

`▲ [WARNING] Duplicate key "price_list" in object literal

    ../posawesome/posawesome/public/js/posapp/components/pos/Invoice.vue:1408:12:
      1408 │             price_list: this.get_price_list(),
           ╵             ~~~~~~~~~~

  The original key "price_list" is here:

    ../posawesome/posawesome/public/js/posapp/components/pos/Invoice.vue:1403:12:
      1403 │             price_list: this.pos_profile.selling_price_list,`

erpnext version 14.17.3
frappe version 14.26.2
posawesome version 4.1.1

**Comment by alirayya1** [comment]
same issue here 
erpnext version 14.17.4
frappe version 14.26.2 
posawesome version 4.1.1

thanks in advance

**Comment by lstbrian** [comment]
> same issue here erpnext version 14.17.4 frappe version 14.26.2 posawesome version 4.1.1
> 
> thanks in advance

do you know what does that mean?

**Comment by alirayya1** [comment]
just comment out 
    // price_list: this.get_price_list(), line 1408 in apps/posawesome/posawesome/public/js/posapp/components/pos/Invoice.vue
thats what i did on my end and app is building normally now

**Comment by lstbrian** [comment]
> just comment out // price_list: this.get_price_list(), line 1408 in apps/posawesome/posawesome/public/js/posapp/components/pos/Invoice.vue thats what i did on my end and app is building normally now

when u comment out, did u re-run the entire command of instalaltion? I mean which one of the following did you run next after u comment out?:

1.bench get-app https://github.com/yrestom/POS-Awesome.git
2.bench setup requirements
3.bench build --app posawesome
4.bench restart
5.bench --site [your.site.name] install-app posawesome
6.bench --site [your.site.name] migrate

**Comment by alirayya1** [comment]
just ignore step one as you already have it installed
