### ISSUE TITLE
Setting card view by default, instead of list view. As a global setting, or maybe per POS profile.[Feature request]: 

### ISSUE THREAD

**Issue by muchai** [yrestom/POS-Awesome#253]
Setting card view by default, instead of list view. As a global setting, or maybe per POS profile.

Frappe Framework: v14.26.3 (HEAD)
ERPNext: v14.17.4 (HEAD)
POS Awesome: v4.1.1 (HEAD)

**Comment by yrestom** [comment]
[feat: Options for Default Card View & Default Sales Order](https://github.com/yrestom/POS-Awesome/commit/a79bc0211bb99e86cd7001c13a6452184fc59163)
