### ISSUE TITLE
Qty in stock doesn't show on card view, displays on list view only.[Feature request]: 

### ISSUE THREAD

**Issue by muchai** [yrestom/POS-Awesome#254]
Qty in stock doesn't show on card view, displays on list view only.

Please have qty in stock also displayed on card view.

Frappe Framework: v14.26.3 (HEAD)
ERPNext: v14.17.4 (HEAD)
POS Awesome: v4.1.1 (HEAD)

**Comment by yrestom** [comment]
[feat: display item qty in items card](https://github.com/yrestom/POS-Awesome/commit/c05070462d43a4985ff7ec50bdf5d5d42db1dc47)
