### ISSUE TITLE
[Feature request]: Customer Group Change

### ISSUE THREAD

**Issue by olamide2** [yrestom/POS-Awesome#28]
We need to be able to change Customer Group when creating customers at PoS

**Comment by elan-k** [comment]
Yes, this may help in terms of selecting the appropriate price list. 

Also if any customer group filter applied at POS Profile. (No customer group filter applied at POS-Awesome as of now)

**Comment by CloudERPng** [comment]
Hi @yrestom any update on this?

**Comment by yrestom** [comment]
[fix: filter the customers from customer groups in pos profile](https://github.com/yrestom/POS-Awesome/commit/773689f4b4979f0c648bbc381fb4e2834e08b5ad)
