### ISSUE TITLE
Hello everyone, I have 19,600 Items, and the item list takes approximately 2 minutes to load in POS Awesome. Please what could be the reason for this and how can I resolve it ?

### ISSUE THREAD

**Issue by brevicconsult** [yrestom/POS-Awesome#280]
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

**Comment by yrestom** [comment]
@brevicconsult If the problem persists, please let me know

**Comment by yrestom** [comment]
There is an option in POS Profile called "Use Server Cache" it will use Redis cache on the server to speedup initial loads of POS Awesome
And you can specify the cache duration also as it required 
[feat: Use Redis cache](https://github.com/yrestom/POS-Awesome/commit/3235e9a40799844272aa74a8b3ea74f5d070f316)
