### ISSUE TITLE
[BUG]: Remove mandatory for Territory during capturing new customer

### ISSUE THREAD

**Issue by muchai** [yrestom/POS-Awesome#287]
Remove mandatory for Territory during capturing new customer

### Versions

Frappe Framework: v14.31.0 (HEAD)
ERPNext: v14.20.1 (HEAD)
POS Awesome: v4.2.2 (HEAD)

### What is Expected?
Territory is optional during capturing new customer on POS Awesome.

### Additional context
This is a reversal of an earlier request to make it mandatory.

**Comment by yrestom** [comment]
In that case, what should we use as a default value in your opinion?

**Comment by muchai** [comment]
We leave it blank, it accepts None value. Or 'Prefer not to say', if not mentioned.
