### ISSUE TITLE
[BUG]: List of territories is being filtered out when creating a new customer on POS Awesome

### ISSUE THREAD

**Issue by muchai** [yrestom/POS-Awesome#288]
The system seems to only display the 20 last modified territories. And one cannot search for a territory that exists.

### Versions

Frappe Framework: v14.31.0 (HEAD)
ERPNext: v14.20.1 (HEAD)
POS Awesome: v4.2.2 (HEAD)

### What is Expected?
Display, or ability to search for all existing territories.
![image](https://user-images.githubusercontent.com/1822868/230170726-29bdd983-816d-46de-a88d-a61b70c7ce35.png)

### What is actually happening?
![image](https://user-images.githubusercontent.com/1822868/230170601-f1e367ae-d55c-48a0-a9f4-da2d81ea45cf.png)

**Comment by yrestom** [comment]
The page must be refreshed in order for the point of sale to be updated with the new data

**Comment by muchai** [comment]
![image](https://user-images.githubusercontent.com/1822868/230409803-5b252e89-8051-4195-a3b8-f801300b5ced.png)
79 of them, but displays only the 20 recently modified.

And searching for the older ones, returns Territory not found.
![image](https://user-images.githubusercontent.com/1822868/230410908-0cce2619-c4eb-4da0-9f93-f4402c2d0957.png)
