### ISSUE TITLE
[Feature request]: Change posting Date from Pos Awesome 

### ISSUE THREAD

**Issue by olamide2** [yrestom/POS-Awesome#29]
We need to be able to change posting date from PoS Awesome. This is needed for instances when user needs to post back dated entries.

This should be controlled by an option in PoS profile

**Comment by elan-k** [comment]
Why should we do the backdated entries at the POS level? This can be achieved at the Sales Invoice on Accounts Receivable.

In general, POS helps people to combine the invoicing, payment collection and shipment/delivery together at the time of sale itself. 

**@olamide2 : Can you please help me to understand your requirement better?**

**Comment by yrestom** [comment]
It is common in point of sale that sales are recorded on the same date and time that the transaction occurs
If it is required to prepare sales invoices with special settings, the sales invoices from Erpnext can always be used
