### ISSUE TITLE
[Feature request]: And some different color for cards/lines(if list view) with qty

### ISSUE THREAD

**Issue by muchai** [yrestom/POS-Awesome#295]
### Describe the solution you'd like

In most cases, people want to see even items with no qty on POS. And raise orders for them, for tracking demand vis a vis supply.

As such, there's a need to show either specific card/line(if list view), or qty figure, in some conspicuous color.

Make life a bit easier for users.

**Comment by yrestom** [comment]
[update: different colors for rate & qty](https://github.com/yrestom/POS-Awesome/commit/4561899f36b366b1e17834d7eb922da1437cfd89)
