### ISSUE TITLE
[BUG]: Different amount showing up in MPESA customer popup than what is sent from the system invoice

### ISSUE THREAD

**Issue by muchai** [yrestom/POS-Awesome#296]
Different amount showing up in MPESA customer popup than what is sent from the system invoice

### Versions

Frappe Framework: v14.31.0 (HEAD)
ERPNext: v14.20.3 (HEAD)
POS Awesome: v4.2.3 (HEAD)

### Steps to reproduce

Order in the system
![image](https://user-images.githubusercontent.com/1822868/230658187-345fcdc7-5c43-4afc-8efd-272d1cfd6b60.png)

Payment request.
![image](https://user-images.githubusercontent.com/1822868/230658445-9349c828-bf60-4a8b-8274-cb1337596cef.png)

What pops up for the customer.
![WhatsApp Image 2023-04-07 at 21 27 22](https://user-images.githubusercontent.com/1822868/230659277-14100ed8-3d27-4ba7-ab08-0223f154a064.jpg)

Second request, same order.
![WhatsApp Image 2023-04-07 at 21 27 22](https://user-images.githubusercontent.com/1822868/230659306-727cfab8-d57a-4fc5-be90-2d8d9ae8d77d.jpg)

For same request, it popped 10 KES.

### What is actually happening?
402.00, KES should be the amount that pops up for payment.

### Additional context
Integration Request
{
 "currency": "KES",
 "payment_gateway": "Mpesa-Mpesa Express",
 "payment_reference": "SINV-2023-00364",
 "reference_docname": "ACC-PRQ-2023-00035",
 "reference_doctype": "Payment Request",
 "request_amount": 20.0,
 "sender": "0723xxxxxx"
}

**Comment by yrestom** [comment]
I am unable to reproduce the problem

**Comment by muchai** [comment]
Thing with this is, it happens in some cases, and not others.

**Comment by muchai** [comment]
Clearing past, failed, integration requests, and pending payment requests, seems to resolve the issue.

After clearing those, we end up with one payment request, multiple integration requests, for each re-request for the same invoice.

There're two refences for POS Invoice here, not sure if we should handle the same for Sales Invoice.https://github.com/frappe/erpnext/blob/develop/erpnext/erpnext_integrations/doctype/mpesa_settings/mpesa_settings.py

Line: 206, frappe.db.set_value("POS Invoice", pr.reference_name, "mpesa_receipt_number", mpesa_receipts)

Line 217: doctype="POS Invoice",

**Comment by yrestom** [comment]
I've tried this scenario and it seems working fine

**Comment by muchai** [comment]
Described in detail here (https://github.com/frappe/erpnext/issues/34802). Issue is on ERPNext side.
