### ISSUE TITLE
Installed on V12 but missing a fil

### ISSUE THREAD

**Issue by Helkyd** [yrestom/POS-Awesome#3]
Hi,
First of all nice work and keep up.
Maybe should not but still using V12 and gave a try to install.. and did well but when opening the POSAPP the below message was shown:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/development/frappe-bench/apps/erpnext/erpnext/selling/page/point_of_sale/onscan.js'

Where to find this onscan.js ?

Opppps sorry found out that is part of V13... reason why you said from V13 on words... Sorry and thanks

**Comment by yrestom** [comment]
Now it's support Erpnext V12 you can try it from beta4 branch
