### ISSUE TITLE
[BUG]: When searching for items, barcode isn't recognized.

### ISSUE THREAD

**Issue by nbjayme** [yrestom/POS-Awesome#302]
## Versions

Frappe Framework: v13.18.0 (version-13)
ERPNext: v13.18.0 (version-13)
POS Awesome: v3.5.1 (version-13-hotfix)

### What is Expected?

When typing a code it should allow searching for barcode instead of just item_code, or allow 
search default option.  If barcode, then it must display the barcode and allow search via barcode.

### What is actually happening?

POS search by item code and not barcode.

**Comment by yrestom** [comment]
Currently, it searches the barcodes, but after it searches the item code and the name of the item, if you complete writing the barcode, it will display the corresponding item
