### ISSUE TITLE
[BUG]: When you uninstall app you get a lot of errors

### ISSUE THREAD

**Issue by bigerx** [yrestom/POS-Awesome#310]
When you uninstall app it conflicts with other custom apps.
So others please be careful if you want to test it install it on frappe where you are testing things couse if you remove it you'll get a lot of errors and i didnt find any documentation about uninstalling..

**P.S: It's a great custom app forgot to mention just didn't suit my needs for now!**

- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

**Comment by yrestom** [comment]
Can you list these errors here so that we can fix them?

**Comment by bigerx** [comment]
> h

On module sales, when you try to open sales invoice that i have saw, purchace invoice aswell and i'm gonna check for more and give you more informations. Couse i had to send back server in time with snapshot i had.. so i will install again and let you know after i clone that server

**Comment by yrestom** [comment]
Related: https://github.com/yrestom/POS-Awesome/issues/211
