### ISSUE TITLE
[BUG]: Request time out

### ISSUE THREAD

**Issue by Sasa15966562** [yrestom/POS-Awesome#313]
### Versions

- Frappe: v13.52.0 
- Erpnext: v13.49.11
- POS Awesome: v3.5.1

### What is actually happening?

Greetings, I've installed pos awesome on my erpnext website, and whenever I open it it keeps crashing with an error "request timed out" Not showing any product data also but the customers data is there, Whenever I give it any order or action, it doesn't respond and the while app crashes till it gives me aa request timed out.

### Screenshots

![downtown](https://github.com/yrestom/POS-Awesome/assets/95691691/f60db143-2a65-4acb-84f0-a2c4e3e1d673)

**Comment by yrestom** [comment]
Can you please find out if any errors in the browser console?

**Comment by Sasa15966562** [comment]
this is what is shown when this error message appears 
![failure](https://github.com/yrestom/POS-Awesome/assets/95691691/9c033ad8-6c8f-46ee-91d7-6dceedc12cf2)

**Comment by yrestom** [comment]
What are the specifications of the server you are using?
And how many customers and items do you have?
