### ISSUE TITLE
[Feature request]: Limit the items when searching/calling items

### ISSUE THREAD

**Issue by Madcheese101** [yrestom/POS-Awesome#316]
Hello,

Is it possible to change the way how calling the products works?

For now, it calls all the products at once and therefore it will take some time to load for the first time for businesses that has product variants above 5000.

The original ERPNext POS is a great example for performance, it limits the items result and calls the `get_items()` method whenever an item_group or search term filters fields are changed.

If possible, I would like to know, if I were to implement the ERPNext version of calling the `(get_items()) `method, what parts of your project would be affected other than listing the items in the POS interface and filtering it?

I hope that you take this into consideration.

**Comment by yrestom** [comment]
Hello 
If you are using Version 14 there is a new feature in Frappe https://github.com/frappe/frappe/pull/20452 for speed up POS Awesome [feat: Use Redis cache](https://github.com/yrestom/POS-Awesome/commit/3235e9a40799844272aa74a8b3ea74f5d070f316) with an new option in POS Profile "Use Server Cache" 

Please try it and let me know what your thought

**Comment by Madcheese101** [comment]
Unfortunately not 😔

**Comment by Madcheese101** [comment]
Unfortunately, I use v13

**Comment by yrestom** [comment]
I think it will be better if it is optional, like having an option for this in POS Profile.

**Comment by Madcheese101** [comment]
I thought the same thing.

Once I finish fixing the other bugs I will try and make it optional, then I will submit a pull request.
