### ISSUE TITLE
TAX Issue 

### ISSUE THREAD

**Issue by sammish** [yrestom/POS-Awesome#32]
Dear Team. 

Tax Not display in POS Awesome 

![image](https://user-images.githubusercontent.com/12432802/106149593-7f5bc080-618b-11eb-8300-59b49d40027d.png)
![image](https://user-images.githubusercontent.com/12432802/106149686-9b5f6200-618b-11eb-8110-30aa8911f94b.png)
![image](https://user-images.githubusercontent.com/12432802/106149766-ae723200-618b-11eb-9f1a-2781c636db35.png)

**Comment by yrestom** [comment]
POS Awesome can only do tax inclusive. Meaning you have to include the tax in the price.
