### ISSUE TITLE
[BUG]: customer icons suddenly disappeard

### ISSUE THREAD

**Issue by ahmed751995** [yrestom/POS-Awesome#324]
i am using version-14 every thing was working fine, but suddenly the customer icons disappeared and type also disappeared 
[the current pos awesome](https://pasteboard.co/bNjEfOwDro21.jpg)

**Comment by Mustafa-Regis** [comment]
I have the same problem, did you solve it or do you know what is the reason?

**Comment by ahmed751995** [comment]
the cause of the problem was that my country disabled access to some libraries which the app depends upon, so you have to replace it or use VPN

**Comment by Mustafa-Regis** [comment]
Thank you very much, it turned out to be the same problem and it was tested on a VPN program and temporarily solved. Now I will try to find a permanent solution
