### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by GalactoseNotFOund** [yrestom/POS-Awesome#329]
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

### Steps to reproduce

1. Go to 'awesomebar'
2. Click on 'posawesome'
3. doesn't open posawesome

### What is Expected?
open posawesome

### What is actually happening?
its show nothing

### Additional context
<img width="626" alt="image" src="https://github.com/yrestom/POS-Awesome/assets/108864416/7e33f0d5-ad8a-41ef-906c-d2089ed6f790">

### Screenshots
<img width="960" alt="image" src="https://github.com/yrestom/POS-Awesome/assets/108864416/dc6a9391-2a8b-4209-b18d-00b542edef12">

**Comment by yrestom** [comment]
You should use branch version-13 not develop branch
