### ISSUE TITLE
[BUG]: there was arrows when add item in invoice but after chrome new updates these features are uncompatible right now

### ISSUE THREAD

**Issue by BOB1212121** [yrestom/POS-Awesome#330]
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

**Comment by tedyswaga** [comment]
provide more information

**Comment by BOB1212121** [comment]
![image](https://github.com/yrestom/POS-Awesome/assets/86354095/dfbe9e1a-761f-4338-bc12-bceee75e4b74)

now It's disappeared

**Comment by BOB1212121** [comment]
![image](https://github.com/yrestom/POS-Awesome/assets/86354095/d351ef94-b766-4bab-bc3d-dbb615a1463e)

**Comment by BOB1212121** [comment]
> provide more information

Thanks in Advance

**Comment by tedyswaga** [comment]
Does the client machine have access to Internet?

**Comment by BOB1212121** [comment]
The ubuntu machine no but the windows yes

**Comment by tedyswaga** [comment]
The only time have seen this the client machine did have Internet. Inspect the page to see if it has any errors

**Comment by BOB1212121** [comment]
No it doesn't connected to the internet and the inspect has no errors Sir and the same problem in my device and two customer devices

**Comment by BOB1212121** [comment]
If you can help I appreciate it 🙏 can we contact and share the problem with you to help ?

**Comment by tedyswaga** [comment]
Teddymutuma@gmail.com, u can send an email
