### ISSUE TITLE
[QUESTION]:  How does posawesome handles Allow Submissions in background job

### ISSUE THREAD

**Issue by tedyswaga** [yrestom/POS-Awesome#331]
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/blob/2883adc72d515ef3b9572a89b6de6ae14ae87eae/posawesome/posawesome/api/posapp.py#L592
