### ISSUE TITLE
[Feature request]: Auto Select the Batch on POS 

### ISSUE THREAD

**Issue by elan-k** [yrestom/POS-Awesome#34]
### Problem : 

It's a great option to have a selectable batch number field on the POS. 

But in general, we use POS to do faster transactions on B2C businesses, since there are lots of billing / invoicing required daily. 

So selecting the batch on every item and every invoice is going to be a much difficult task for B2C businesses. 

### Solution :

We can consider the following points to make the batch selection automatic for the retail environment, 

1. Auto-select if we have a single batch available for that item and invoice. 
2. Auto-select based on the Expiry Date on the batch if we have multiple batches for that item and invoice 
3. Show pop-up type batch selection option if unable to Auto-select

Also, we can have the settings for Auto-select at the POS Profile Level for user preferences on the auto selection. 

This option will make life easier for the end-user / cashier in the retail B2C environment. 

![InkedBatch Selection_LI](https://user-images.githubusercontent.com/78781781/107487478-356fd300-6bac-11eb-952a-3018c944759d.jpg)

**Comment by elan-k** [comment]
@yrestom : Any Updates on this?

This definitely improves the life of the system operator/cashier since they do not need to select the batch on individual items. But at the same time, they can overwrite the Auto-Selection at the POS.

**Comment by yrestom** [comment]
I will try to work on this in the next few weeks

**Comment by elan-k** [comment]
@yrestom : Any Updates on this?

**Comment by CloudERPng** [comment]
Hello @yrestom 

Any update on this? Having a Batch Selection Pop up would be awesome

**Comment by elan-k** [comment]
@yrestom :   Any Updates on this?

**Comment by yrestom** [comment]
[feat: auto set batch](https://github.com/yrestom/POS-Awesome/commit/36c73854e34fca926536bae024e1201f93dfb950)
