### ISSUE TITLE
[BUG]:  errors on new install 

### ISSUE THREAD

**Issue by hifyaan** [yrestom/POS-Awesome#349]
hi i am getting an error installing pos awesome new installation
erpnext 14.x.x-develop
frappe 15.x.x-develop
payments 0.0.1
posawesome 6.0.4

the error is 
node esbuild --production --apps posawesome --run-build-command
✘ [ERROR] [plugin vue] v-model cannot be used on a prop, because local prop bindings are not writable.
Use a v-bind binding combined with a v-on listener that emits update:x event instead
✘ [ERROR] [plugin frappe-vue-style] Cannot read properties of undefined (reading 'outputs')

 ERROR  There were some problems during build

Terminated
error Command failed with exit code 143.

subprocess.CalledProcessError: Command 'yarn run production --apps posawesome --run-build-command' returned non-zero exit status 143.

**Comment by ankush** [comment]
```
yarn run v1.22.19
$ node esbuild --production --apps posawesome --run-build-command
✘ [ERROR] [plugin vue] v-model cannot be used on a prop, because local prop bindings are not writable.
Use a v-bind binding combined with a v-on listener that emits update:x event instead.

    ../posawesome/posawesome/public/js/posapp/components/pos/OpeningDialog.vue:5:6:
      5 │ dialog
        ╵       ^

  The plugin "vue" was triggered by this import

    ../posawesome/posawesome/public/js/posapp/components/pos/OpeningDialog.vue:1:159:
      1 │ ...der } from "/home/frappe/frappe-bench/apps/posawesome/posawesome...
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```




Same error when running pos-awesome on v15-beta branch. Seems like small fix. @yrestom
