### ISSUE TITLE
[BUG]: Quantity Field rounded to 2 Decimal Places

### ISSUE THREAD

**Issue by elan-k** [yrestom/POS-Awesome#35]
### Versions

ERPNext: v12.16.2 (version-12)
Frappe Framework: v12.13.0 (version-12)
POS Awesome: v1.0.2 (master)

### Steps to reproduce

1. Open POS Awesome
2. Complete the Shift Opening Form
3. Click on the Item to bill and provide quantity in 3 decimal points like 1.258
4. Check the Qty of the item in the billable list, It has only 2 decimal points like 1.26 

### What is Expected?

It's expected to have quantity in 3 decimal points since kilograms and grams are being measured in 3 decimal points widely like,

975 g or 0.975 kg
1.725 kg 
12.253 kg
124.569 kg

We use 2 decimal places for the money field only.

### What is actually happening?

On the billable item list, the quantity (QTY) of the item has been rounded to 2 decimal places. 

But the amount calculated at the end of the row ie 275.50 (1.258 X 219) is not having issues. 

### Screenshots
![Three Decimal Points](https://user-images.githubusercontent.com/78781781/107733010-e8147280-6d1f-11eb-9cb9-d24dfcf5cf53.PNG)

**Comment by elan-k** [comment]
This is just a display issue (low priority). Everything gets **updated properly** in the background.  So no issues with this one. 

### Screenshots
![Three Decimal Points_Update](https://user-images.githubusercontent.com/78781781/108402105-1b389380-7243-11eb-8dd7-615ec0c97f5f.PNG)

**Comment by yrestom** [comment]
That's right, we can come back to it later and fix it if it causes a problem
Thank you
