### ISSUE TITLE
when we enter customer name or number from footer its giving error "TypeError: set_customer_info() missing 1 required positional argument: ‘customer’ "[BUG]: 

### ISSUE THREAD

**Issue by zahidshuja** [yrestom/POS-Awesome#36]
when we enter customer name or number from footer its giving error "TypeError: set_customer_info() missing 1 required positional argument: ‘customer’ "

- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

**Comment by elan-k** [comment]
plz attach the screenshot and steps to reproduce the issue

**Comment by yrestom** [comment]
Please provide us with more details and screenshots
