### ISSUE TITLE
[BUG]: Sales tax not calculating on sales invoice because of POSAwesome

### ISSUE THREAD

**Issue by Rick-Hard89** [yrestom/POS-Awesome#362]
Me and another user on the frappe forums ran into the same issue.
I was on a clean install of ERPNext i also had POSAwesome installed and some other modules. When creating a new invoice from a timesheet the tax would be calculated on the invoice but as soon as we hit save the tax disappeared. Also when trying to import items from a sales order into the same invoice the items would not get added to the item list.

Another unrelated bug: I also did some changes to customize forms and then reset everything to default and got an error for missing attribute in customsalesinvoice for posa_coupons or something similar. it disappeared after i did a bench migrate. I don’t know much about this software but the unrelated bug, and the fact that the other person also uses posa, led me to believe that posa changes the default erpnext forms in some way to make it compatible with its module and this is what causes some error with the tax calculations. 
Correct me if I'm wrong.

This is the modules i used when it happened and their versions. I removed the whole frappe folder and reinstalled all the modules except POSAwesome and the problem disappeared.
![erp_version](https://github.com/yrestom/POS-Awesome/assets/128173084/c49eca6f-1c9f-43e9-a34b-9e24f6729f24)

Here you can read our forum post:
https://discuss.frappe.io/t/sales-taxes-are-zeroed-out-on-invoice-but-present-on-sale-order/107822

**Comment by multidoc** [comment]
Same issue

**Comment by muchai** [comment]
This is tied to creation of invoice, from timesheet, not POS Awesome.
The issue still exists in an environment with no POS Awesome.
Test, creation of invoice directly, it will calculate taxes as expected.
Should be raised ON ERPNext issues.

**Comment by Rick-Hard89** [comment]
> This is tied to creation of invoice, from timesheet, not POS Awesome. The issue still exists in an environment with no POS Awesome. Test, creation of invoice directly, it will calculate taxes as expected. Should be raised ON ERPNext issues.

This is not true. I don't have POSAwesome installed at the moment and i can create both invoices from timesheets and sales orders with the vat being saved successfully. Clearly this has something to do with POSAwesome because it works perfect without it.
Have you tried it on a clean installation with the newest verison?
