### ISSUE TITLE
[BUG]: Unable to select income account while creating pose profile. It only allows creating a new account rather than selecting existing one

### ISSUE THREAD

**Issue by kumuduraj** [yrestom/POS-Awesome#368]
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

### Steps to reproduce

4. See the error

### Screenshots
If applicable, could you add screenshots to help explain your problem?

**Comment by kumuduraj** [comment]
![ice_screenshot_20230806-015638](https://github.com/yrestom/POS-Awesome/assets/13012037/8d31b216-2bfa-47f9-bdff-b0e80fecba80)

**Comment by yrestom** [comment]
This is Erpnext issue
