### ISSUE TITLE
Shift Close[BUG]: 

### ISSUE THREAD

**Issue by zahidshuja** [yrestom/POS-Awesome#37]
when we close shift, the amount in closing shift is not changing

- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

**Comment by elan-k** [comment]
Are you talking about the "[Error in Expected Amount On Shift Closing Screen](https://github.com/yrestom/POS-Awesome/issues/33)" ?

Or something else ?

**Comment by zahidshuja** [comment]
No
i am saying when we click on the closing screen,
We insert amount then it's not saving very difficult to same image

**Comment by zahidshuja** [comment]
When we press enter its ok, but when we click somewhere else in screen value not saving in the field. 
many POS device don't have keyboard or mouse its very difficult to save values in the 
![5](https://user-images.githubusercontent.com/79209720/109187405-f001f700-77a2-11eb-9a80-bace01015e7c.JPG)
closing amount

**Comment by yrestom** [comment]
Please follow [Issue Guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines)
