### ISSUE TITLE
[BUG]: Discount not showing while select the item/product but will displayed after Save or Print Draft

### ISSUE THREAD

**Issue by mkashif1973** [yrestom/POS-Awesome#375]
While selecting the product from items it will showing no discount (see below):
![image](https://github.com/yrestom/POS-Awesome/assets/111403440/55cd877f-8d4d-4225-b4a4-d6509dc16235)

but once we save/new and print draft it will calculate the discount and save accurately (see below):

![image](https://github.com/yrestom/POS-Awesome/assets/111403440/951f0eb8-4372-44b8-8699-32967487a5f8)

erpnext 14.34.3
frappe 14.44.0
posawesome 6.1.2

Please help to resolve this issue so users can view the discounts on selection as well.

Regards,

Kashif

**Comment by yrestom** [comment]
POS Awesome not support Pricing Rules, please use POS Offers instead, and disable Pricing Rules from POS Profile

**Comment by mkashif1973** [comment]
I did the same you advised but no luck.

I disabled the pricing rule and then set the discount on POS Profile, but now no discount showing even after I save the invoice.

**Comment by mkashif1973** [comment]
Sorry, please ignore above message it is working, by closing shift and re-open.

but at this time we are getting some prices getting value while other need to expand and then rate will appear see below:

![image](https://github.com/yrestom/POS-Awesome/assets/111403440/e7e8809e-cfda-4ac2-8020-a18ede136d19)

after expand rate automatically fetched
![image](https://github.com/yrestom/POS-Awesome/assets/111403440/31f2767b-b72f-480a-92ad-36435aaaa4b7)

Also I wish to add the quantity of same item in existing list but it will add the new line of same item, how can i do this?

**Comment by yrestom** [comment]
@mkashif1973 Can you please share the POS Profile
