### ISSUE TITLE
[BUG]: How to enable / disable POS functions

### ISSUE THREAD

**Issue by mkashif1973** [yrestom/POS-Awesome#376]
Can you please confirm how do we enable/disable user access on following:

CANCEL
HELD
PAY
PRINT/DRAFT

This is required because in some stores there are different counter for sell, packing and payments so in this case store is willing to give some users rights to create only Order/Invoices but no access to receive the payment and wise versa some user need to provide access to HELD order/invoices and payment option ONLY. Please guide us if you have this feature enabled then how we manage this 

Kind Regards,

Kashif

**Comment by yrestom** [comment]
For PRINT/DRAFT there is an option for that in POS Profile called "Allow Print Draft Invoices"
For the others there is no options to control them 
It is not support use case like this

**Comment by mkashif1973** [comment]
You mean we cannot restrict users to make payment entries ?

**Comment by yrestom** [comment]
From POS page yes, we cannot restrict users from completing the process and submitting the invoice and its payment

**Comment by mkashif1973** [comment]
ok, understand.

At the moment only same profile user's can access "Draft Invoices" But will it be possible that on multiple POS profile user can access/view on "HELD INVOICES" so then it can be control easily in your POS-AWESOME. 
I must appreciate it is very awesome work you did in this POS module.

Kind Regards,
