### ISSUE TITLE
[BUG]: Available Quantity in Item List is not getting refresh after creating Sale

### ISSUE THREAD

**Issue by umarless** [yrestom/POS-Awesome#382]
Available Quantity in Item List is not getting refresh after creating Sale.

Also after refreshing page the available quantity shows zero.

And then when I switch between Item Groups, actual quantity shows back.  

### Versions

App         Version - Branch
erpnext - 14.38.0 - version-14
frappe - 14.48.1 - version-14
posawesome - 6.1.3 - develop

### Steps to reproduce

1. Go to 'POSAwesome'
2. Select Item to Sale
3. Check the Item Available Quantity before and after Sale
4. See the error

### What is Expected?

After every transaction of sale, Item available quantity should be refresh,

### What is actually happening?

After every transaction of sale, Item available quantity not getting refresh.
After clicking on Refresh/Reload Its shows 0.000 in available quantity.

### Screenshots

![image](https://github.com/yrestom/POS-Awesome/assets/97974556/7c49ffa9-e939-4653-9a0f-d43970063948)

![image](https://github.com/yrestom/POS-Awesome/assets/97974556/c1281603-66a0-4139-82ad-6394f29fa765)

**Comment by QazCyber** [comment]
i have the same issue, any updates?

**Comment by yrestom** [comment]
This is normal behavior because it only refreshes the quantities when the user searches for a product.
At the same time also it should show the updated quantities if the user refreshes the page

@umarless  Can you please share the POS Profile

**Comment by yrestom** [comment]
A quick fix, uncheck the "Use Browser Local Storage" option from "POS Awesome Advance Settings"

**Comment by yrestom** [comment]
Now it should refresh after changing the customer 
https://github.com/yrestom/POS-Awesome/commit/f785d6bac352e3f7a5d9c2b7dcc6c2904653a4b9
I hope this will help
