### ISSUE TITLE
[BUG]: Sales Return Refund Amount

### ISSUE THREAD

**Issue by thida-bcn** [yrestom/POS-Awesome#386]
When we made Sales Return, for Refund
we can't made payment
![image](https://github.com/yrestom/POS-Awesome/assets/62122640/1b970b61-a706-4c51-8415-0f629ce7aa77)
that cause unbalance amount in close shift
1 Sales Invoice and 1 Sales Return
![image](https://github.com/yrestom/POS-Awesome/assets/62122640/da303fcd-7c95-4deb-80ab-8e4b9c2f59e7)
Expected Amount must be 0
now system shown only Sales Amount
![image](https://github.com/yrestom/POS-Awesome/assets/62122640/36e92631-01c0-4ff6-aaaf-bbcf81fb5c69)
that cause outstanding invoices
![image](https://github.com/yrestom/POS-Awesome/assets/62122640/e9fdd6c7-380d-4f1f-ad7c-8bf70040f377)
application version : 6.1.3
previous version is working well version: 3.6.0
![image](https://github.com/yrestom/POS-Awesome/assets/62122640/ebf56d49-7009-43bd-a033-6a233dec6584)

**Comment by thida-bcn** [comment]
@

**Comment by thida-bcn** [comment]
it

> @

it was ok now
we had to click cashbook for return
thank you

**Comment by N1RMS** [comment]
> it
> 
> > @
> 
> it was ok now we had to click cashbook for return thank you

I am facing the same issue. I cannot understand your fix. Cashback is enabled while making the return. It is still not deducting from expected amount
