### ISSUE TITLE
Template is not Responsive [BUG]: 

### ISSUE THREAD

**Issue by zahidshuja** [yrestom/POS-Awesome#39]
The template is not responsive, if we change screen size all icons get on top of each. 

- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

**Comment by elan-k** [comment]
plz attach the screenshot

**Comment by zahidshuja** [comment]
#Hi
Please find attched screen short
![1](https://user-images.githubusercontent.com/79209720/109186977-84b82500-77a2-11eb-9d29-3bcec8964d3e.JPG)
![2](https://user-images.githubusercontent.com/79209720/109186979-85e95200-77a2-11eb-9a9c-981306f6c7ae.JPG)

``

**Comment by yrestom** [comment]
POS Awesome does not support this size or resolution of the screens
