### ISSUE TITLE
[BUG]: In Printout TAX Value not showing

### ISSUE THREAD

**Issue by zahidshuja** [yrestom/POS-Awesome#41]
Hi 
when I post an invoice its posting everything well but there is a bug its not showing TAX value in print format.  i went on invoice module and check print format

 from there as well same result not showing TAX value there as well, 

![3](https://user-images.githubusercontent.com/79209720/109186874-6b16dd80-77a2-11eb-82de-e966bc6b4916.JPG)
![4](https://user-images.githubusercontent.com/79209720/109186880-6baf7400-77a2-11eb-8ef4-0e926fdf56ff.JPG)

- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

**Comment by yrestom** [comment]
This from printing format 
please review :
https://docs.erpnext.com/docs/user/manual/en/customize-erpnext/print-format
https://docs.erpnext.com/docs/user/manual/en/setting-up/print/print-format
https://docs.erpnext.com/docs/user/manual/en/setting-up/print/print-format-builder
