### ISSUE TITLE
Credit Sales : Due Date

### ISSUE THREAD

**Issue by thida-bcn** [yrestom/POS-Awesome#418]
Credit Sales Due Date didn't change
![image](https://github.com/yrestom/POS-Awesome/assets/62122640/71add163-05da-472d-85af-d46209cc1c68)

![image](https://github.com/yrestom/POS-Awesome/assets/62122640/97e3c09d-9ce1-45df-a0bc-904da05aad69)
![image](https://github.com/yrestom/POS-Awesome/assets/62122640/5dc26391-201c-42a2-af4a-f804883c8793)

**Comment by Anurangenie** [comment]
Having the same issue. I an you have the issue of Due date disappearing on your sales invoice too.
For a split second the non updated due date shows up and disappears.

![Screenshot (162)](https://github.com/yrestom/POS-Awesome/assets/151640180/ee94adc5-01fd-4462-a0ca-3f3bc2d7b286)
![Screenshot (161)](https://github.com/yrestom/POS-Awesome/assets/151640180/0cffae8c-2f24-4585-b883-19db0c9890eb)
