### ISSUE TITLE
Return nor showing any invoice [BUG]: 

### ISSUE THREAD

**Issue by Yazansammour** [yrestom/POS-Awesome#42]
I created an invoice, then i selected return, the search is not able to find any invoice,

<img width="1361" alt="Screen Shot 2021-03-07 at 8 23 00 AM" src="https://user-images.githubusercontent.com/12206030/110228923-77c3d000-7f1e-11eb-8ea3-13d29bb35b5a.png">

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/e1f8529d0010f9d588225075012671630554141a
