### ISSUE TITLE
[Feature request]: Order Customization On-Spot

### ISSUE THREAD

**Issue by 0FiRE0** [yrestom/POS-Awesome#426]
### Is your feature request related to a problem? Please describe.
No, it is just an enhancement.

### Describe the solution you'd like
If I want to use POS-Awesome for a restaurant.
How can I configure the sellable items, so that I can make some changes upon the customer's request (E.g. adding extra catchup, garlic, or sauce, or even not adding garlic at all ...etc.), and also add some optional notes to the order.

### Describe alternatives you've considered
There could be an alternative solution to use Item Variants, but this will make the items list large, and will be hard for the cashier to select the correct item from the list, or even to modify the order if the customer changes his/her mind in the middle of the order.

### Additional context
It would be nice to have on-the-spot additions to the order, and for each item. (E.g. Having coffee with sugar or no sugar).

I have made a quick prototype of how the item options might be enhanced.
![image](https://github.com/yrestom/POS-Awesome/assets/19993814/bd747b52-5eed-46a2-972c-d576a3061802)

**Comment by 0FiRE0** [comment]
After a dive into the settings, I noticed that the "Additional Notes" feature is already available from the POS Profile Settings.
The only thing remaining that is great to have is the customization with cost and the free ones.

**Comment by yrestom** [comment]
Have you tried using Item templates an variants for that?

**Comment by 0FiRE0** [comment]
> Have you tried using Item templates an variants for that?

Yes, but unfortunately, it is not convenient for the cashier, as he/she will have so many redundant items for the same thing.

Below is an example of Burger having 3 customer options (Catchup, Cheese, and Pickles) resulting in 27 different variants:
![image](https://github.com/yrestom/POS-Awesome/assets/19993814/f7c385d0-d475-42c2-a522-204a4832eaa7)

This is how the Cashier screen will look for the same item but with different variations.
![image](https://github.com/yrestom/POS-Awesome/assets/19993814/71cc2179-a10f-41b1-bbff-662a465c69c6)

**Comment by 0FiRE0** [comment]
A proposed solution could be having a table of items inside the "Item" doctype (Very similar to the Items Table in the Sales Invoice), and let's call it "Modifiers". Where the Administrator can add other items in the Modifiers Table, while setting the limits (E.g. Default Value, Price,  Minimum and Maximum quantity allowed).
Then, in the POS Awesome Screen. once the cashier selects the item (E.g. Burger), the list of Modifiers will be fetched (E.g. Catchup, Cheese, Pickles), and allows the cashier to change them with "+" and "-" upon the customer's request as in the below screenshot.

![287229392-bd747b52-5eed-46a2-972c-d576a3061802](https://github.com/yrestom/POS-Awesome/assets/19993814/a29dcba2-3f8a-4b4d-8dc4-8bcc4a2cff0c)

**Comment by yrestom** [comment]
You can hide variants items and only display the templates items then when he select the burger template item he will see a popup window that allowing him to select the variants items and from that window he can also filter the variants items by clicking on the attributes buttons
I hop this will helps you

**Comment by 0FiRE0** [comment]
This is great, it helped a lot, thank you so much :)

![image](https://github.com/yrestom/POS-Awesome/assets/19993814/0e042d48-a489-4aa4-b8d6-35c14380032b)

**Comment by 0FiRE0** [comment]
BTW, Hiding the variants option is not working, and all variants are showing all the time.
I tried refreshing the items, and the cache, and even disabling the cache and nothing worked.

Is there a specific attribute I need to set in the Variant to make it hidden from the main screen, and shows only in the variants screen?

![image](https://github.com/yrestom/POS-Awesome/assets/19993814/10ea9dcc-8ab4-4d1f-8067-1017b1667d48)

![image](https://github.com/yrestom/POS-Awesome/assets/19993814/46ef0b89-8105-49c2-841b-af2a8f859c21)
