### ISSUE TITLE
[BUG]: POS Awesome app page white page

### ISSUE THREAD

**Issue by Mazenalbanna** [yrestom/POS-Awesome#433]
Hello,
After installing POS Awesome and trying to open pos awesome app only a white page and an error shows in the console
I have tried to install pos awesome without erpnext the pos awesome app successfully opened but specific modules dependencies from the erpnext are required to run pos awesome,
So after installing erpnext the error reoccured

### Versions

erpnext 14.40.0
frappe 14.50.0
posawesome 6.1.3

### Stacktrace / full error message

TypeError: frappe.PosApp is undefined
    on_page_load posapp.js:9
    trigger_page_event pageview.js:102
    Page2 pageview.js:89
    show pageview.js:52
    callback pageview.js:36
    callback request.js:85
    200 request.js:128
    call request.js:294
    jQuery 6
    call request.js:268
    call request.js:105
    with_page pageview.js:29
    show pageview.js:48
    with_doctype model.js:190
    show pageview.js:47
    render_page router.js:323
    render router.js:297
    route router.js:152
    set_route desk.js:164
    startup desk.js:95
    Application desk.js:30
    start_app desk.js:12
    <anonymous> desk.js:25
    jQuery 13
    __require2 libs.bundle.6XLVBACU.js:16
    <anonymous> jQuery
    <anonymous> libs.bundle.6XLVBACU.js:31008

### Additional context
Please can you specify me with the compatible versions

**Comment by yrestom** [comment]
POS Awesome is depends on Erpnext so it should be installed first then you can install POS Awesome

**Comment by Mazenalbanna** [comment]
> POS Awesome is depends on Erpnext so it should be installed first then you can install POS Awesome

Hello Youssef
Thank you for your reply yes i tried both ways With ERPNext previously installed 
But my comment was that the main issue is that there is a misconvenience between the versions of ERPnext and Pos Awesome
so Pos awesome is returning a console error when trying to enter the pos awesome app as mentioned above and a clear white page

**Comment by LeoKogan** [comment]
Here is my log from the browser console
[mydomain.frappe.cloud-1703175347922.log](https://github.com/yrestom/POS-Awesome/files/13743972/mydomain.frappe.cloud-1703175347922.log)

**Comment by LeoKogan** [comment]
Hello Youssef,
I've installed the app and change the plan to subscription But I am not sure how you access the support.

**Comment by yrestom** [comment]
> Hello Youssef, I've installed the app and change the plan to subscription But I am not sure how you access the support.

Please contact me at my email
