### ISSUE TITLE
[Feature request]: Add Product by Serial Number like Standard POS

### ISSUE THREAD

**Issue by ahashad** [yrestom/POS-Awesome#46]
**The Problem**
POS Awesome app can not add products by serial numbers. This is very important feature for many retail like pharmacies.

**The Required Features:**
Add ability to add product to basket by serial number. and update batch number automatically. every serial number must has a single batch number, so it is very easy to detect the batch number of product after scan product serial number by barcode scanner and pos awesome can update all required fields automatically. so the POS worker can easily handle the sales without any manual work.

**Comment by yrestom** [comment]
[feat: Search and add items by Serial Number](https://github.com/yrestom/POS-Awesome/commit/02577086b596d73a91abd46a6c672f024e39e7f5)
