### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by CloudERPng** [yrestom/POS-Awesome#49]
On develop branch, there is an issue with using Custom Print format when printing receipt....

Receipts ignores print format set in POS Profile and still uses the standard print format

To reproduce
- Create a Custom POS Invoice Print Format 
- Set in POS Profile 
- Create Receipt and complete transaction

**Comment by yrestom** [comment]
Please follow [Issue Guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines)
