### ISSUE TITLE
Multiple Companies and user Permission set to have access on two or three

### ISSUE THREAD

**Issue by Helkyd** [yrestom/POS-Awesome#50]
Hi,
When you have more than 3 companies and you remove the default and set user permissions to access only 2 or 3 companies... Pos-Awesome does not allow to select the company and therefore no POS Profile either.
My user has access to 3 companies
![image](https://user-images.githubusercontent.com/20396898/114669574-f4a25080-9cf9-11eb-9856-f2e55cff7694.png)

But when starting POS-Awesome
![image](https://user-images.githubusercontent.com/20396898/114669672-0c79d480-9cfa-11eb-95d5-7e0fdd59bb0e.png)

Can you have a look.

**Comment by yrestom** [comment]
Please follow [Issue Guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines)
