### ISSUE TITLE
[BUG]: Scan barcode on first item with enough qty shows error

### ISSUE THREAD

**Issue by ptdas** [yrestom/POS-Awesome#53]
### Versions

- Frappe: 12.12
- Erpnext: 12.14
- POS Awesome: 1.0.3

### Steps to reproduce

1. Go to POS Awesome page
2. Scan barcode on Item (with enough qty)
3. Click Pay

### What is Expected?

Payment Dialog shown

### What is actually happening?

See error : "The existing quantity for Item XXX is not enough"

### Screenshots

https://user-images.githubusercontent.com/42093370/115514926-d1097800-a2ae-11eb-8eb2-09f54cde5b7d.mp4

**Comment by yrestom** [comment]
Can you please update POS Awesome to version 1.1.0 and check again

**Comment by ptdas** [comment]
Updated to version 1.1.0 and still the same..


https://user-images.githubusercontent.com/42093370/115873860-a9144300-a46d-11eb-8415-5da61fcbb47a.mp4

**Comment by ptdas** [comment]
![image](https://user-images.githubusercontent.com/42093370/115877871-1d50e580-a472-11eb-831d-86161f22ee4d.png)

In Invoice.vue component line 1022, after I add 

item.actual_qty = data.actual_qty

then it will work as expected..

**Comment by yrestom** [comment]
@ptdas can you make PR for this fix?

**Comment by ptdas** [comment]
@yrestom sorry too much modified code in my side...I'm afraid it will affect others

**Comment by yrestom** [comment]
@ptdas Thank you

https://github.com/yrestom/POS-Awesome/commit/c6a24e4b0df9037f8ef1472e6a0faa645cf8831c
