### ISSUE TITLE
[BUG]: Hardcoded Mode Of Payment

### ISSUE THREAD

**Issue by ptdas** [yrestom/POS-Awesome#54]
### Versions

- Frappe: v12.12
- Erpnext: v12.14
- POS Awesome: v1.1.0

### Steps to reproduce

1. Go to POS Awesome page
2. Set transaction (any item any customer)
3. Click Pay
4. Submit Payment

### What is Expected?
Successfuly submitted

### What is actually happening?
Please Set default Cash or Bank account in Mode of Payment Cash

Line 297 in posapp.py shouldn't be hard code...because users possibly doesn't have a "Cash" mode of payment

### Additional context
![image](https://user-images.githubusercontent.com/42093370/115947368-4f555c80-a4f1-11eb-9737-7487c103871b.png)

below is my quick fix
![image](https://user-images.githubusercontent.com/42093370/115947432-cee32b80-a4f1-11eb-9502-54ac80c57463.png)

**Comment by yrestom** [comment]
@ptdas can you make PR for this fix?

**Comment by ptdas** [comment]
@yrestom sorry too much modified code in my side...I'm afraid it will affect others
