### ISSUE TITLE
exit from POS

### ISSUE THREAD

**Issue by amet123** [yrestom/POS-Awesome#57]
Unable to exit from POS when click shift close 
show message 
Error: Data missing in table: POS Transactions

**Comment by yrestom** [comment]
This error it comms when there is no sales invoice submitted for that shift

**Comment by yrestom** [comment]
You can reopen the ticket when new information about the problem is provided

Greetings

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/5d1c7e9f7e3c66e2a5ba5c04de284294e7350aec
