### ISSUE TITLE
[BUG]: Error in change calculations!

### ISSUE THREAD

**Issue by dnyt84** [yrestom/POS-Awesome#59]
ERPNext: v13.5.2 (version-13)
Frappe Framework: v13.5.2 (version-13)
POS Awesome: v2.0.0 (master)

Hello,

when I try to make a sale that is a credit sale I get an error "Error in change calculations!"

I select the customer in the drop down, select the item I want to sell.
I click on Pay and toggle the "is credit Sale" to on.
Then I click on Submit Payment

An error popup comes up with "Error in change calculations!"

I am not sure what I am doing wrong.

Thank you!

Daniel

**Comment by yrestom** [comment]
[fix: Error in change calculations ](https://github.com/yrestom/POS-Awesome/commit/14a6cd33c9cecb9fde0b6c8859358cd1f381a145)
