### ISSUE TITLE
Receipt Pos

### ISSUE THREAD

**Issue by Ismail2929** [yrestom/POS-Awesome#6]
After submit payment, print view just showing {{body}} and cannot print receipt from the pos. Is it my print setting issue?
![image](https://user-images.githubusercontent.com/70574326/96428877-dd931200-1232-11eb-9c0c-10e79617f982.png)

**Comment by yrestom** [comment]
Wich Erpnext & Frappe version do you have?

**Comment by yrestom** [comment]
And please check if it's happening with the default POS.

**Comment by Ismail2929** [comment]
Im using ERPNext: v12.11.2 (version-12) and Frappe Framework: v12.9.1 (version-12) currently. As per check default POS having no issue, receipt showing as per normal. Picture as below for default pos receipt:
![image](https://user-images.githubusercontent.com/70574326/96686255-e14ca300-13b0-11eb-82d5-109b64be5ae2.png)

**Comment by yrestom** [comment]
Should be fixed by this commit 
https://github.com/yrestom/POS-Awesome/commit/25acb4d71450effda155df6d9c361c6d735bef3f

**Comment by Ismail2929** [comment]
i already commit but still having same issue with the receipt payment.

**Comment by yrestom** [comment]
Make sure running ‘bench build’ after you switching the branch to beta5 and then ‘bench restart’
