### ISSUE TITLE
[BUG]: on Payments vue

### ISSUE THREAD

**Issue by Helkyd** [yrestom/POS-Awesome#63]
<!--  Thanks for your time to make POS Awesome better with your feedback 👍

export default {
  data: () => ({
    loading: false,
    pos_profile: '',
    invoice_doc: '',
    loyalty_amount: 0,
    is_credit_sale: 0,
    date_menu: false,
    addresses: [],
    paid_change: 0,
    order_delivery_date: false,
    paid_change_rules: [],
    is_return: false,
    is_cashback: true,
    redeem_customer_credit: false,
    customer_credit_dict: [],
    **invoiceType: 'Inovice',**
  }),

Payment invoicetype should be **Invoice**

**Comment by Helkyd** [comment]
export default {
  data: () => ({
    loading: false,
    pos_profile: '',
    invoice_doc: '',
    loyalty_amount: 0,
    is_credit_sale: 0,
    date_menu: false,
    addresses: [],
    paid_change: 0,
    order_delivery_date: false,
    paid_change_rules: [],
    is_return: false,
    is_cashback: true,
    redeem_customer_credit: false,
    customer_credit_dict: [],
    invoiceType: 'Inovice',
  }),

**Comment by yrestom** [comment]
I did not understand the problem.
Please report the error appropriately using the template.
You can re-open the ticket when the information is provided appropriately.

My greetings
