### ISSUE TITLE
[BUG]: Tax Applied and is Reducing instead of Adding

### ISSUE THREAD

**Issue by Helkyd** [yrestom/POS-Awesome#65]
- POS Awesome: 

### Steps to reproduce

1. Go to 'Tax Template Create Tax and % and on the POS profile add that tax to Taxes and Charges'
2. Click on 'Create new sales from Awesome and see the total being paid...'

### What is Expected?
Should calculate the TAX while on the right List  so user knows what is the total cost of that Item. 
Should also when Paying instead of Reducing, Adding to the Grand total the sum of (Net Total + Taxes total)

### Additional context
Should check normal Sales Invoice. Deductions can be done and TAX can be calculated either based on Grand Total  or Net Total.

### Screenshots
Added
![Screenshot_20210710_114743](https://user-images.githubusercontent.com/20396898/125160468-e89d2200-e174-11eb-9076-aae49a593cdc.png)
![Screenshot_20210710_114904](https://user-images.githubusercontent.com/20396898/125160469-e9ce4f00-e174-11eb-94ab-6296a548a3a6.png)

**Comment by yrestom** [comment]
Pos awesome is currently tax inclusive only.

**Comment by Helkyd** [comment]
Might change for Angola as we need to show... When ready will do a PR if
willing to have it.


Thanks.

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/37b8d111c581f367a90a2634c50e7b658a9eaba1
