### ISSUE TITLE
[BUG]: Shows existing quantity is not enough even if there is stock in the selected Wharehouse

### ISSUE THREAD

**Issue by nadarvinod** [yrestom/POS-Awesome#66]
### Versions

ERPNext: v13.3.1 (version-13)
Frappe Framework: v13.3.0 (version-13)
POS Awesome: v2.0.1 (master)

### What is Expected?
POS order should be allowed to be placed

### What is actually happening?
Error: Existing quantity of the item is not enough

### Additional context
Stock is available in the warehouse selected in the POS profile. It seems it pick some other warehouse when the item is added to cart.
Available Qty field in the cart shows zero

### Screenshots
![image](https://user-images.githubusercontent.com/34533457/126135994-bbe5de0c-b746-4efc-8eda-9802dbee9804.png)

**Comment by yrestom** [comment]
It fixed thanks to @M-Tallal-Habib 
https://github.com/yrestom/POS-Awesome/commit/bcc1f580ee6f390588b3274380a98578ac8303c3
