### ISSUE TITLE
[BUG]: Item Tex Template Are Not Work Properly

### ISSUE THREAD

**Issue by dsk1991** [yrestom/POS-Awesome#77]
When we make invoice with two item
Frist item has two Tex temple
1 5gst with include tax category rate from 1-937
2 12gst with include tax category rate from 938-10000
and second item has same
After we bill
One item take 12gst on 1200 Rate
and
Second Item take 5gst on 1200 Rate
![Capture](https://user-images.githubusercontent.com/91792106/135722224-92d33f78-5412-4ab0-b188-902773e13c18.JPG)

**Comment by yrestom** [comment]
Please use the issue guideline https://github.com/frappe/erpnext/wiki/Issue-Guidelines
