### ISSUE TITLE
[BUG]: Closing Shift with No POS Transactions Throws Error

### ISSUE THREAD

**Issue by dmbabu** [yrestom/POS-Awesome#78]
### Versions

ERPNext: v13.11.1 (version-13)
Frappe Framework: v13.11.0 (version-13)
POS Awesome: v3.0.1 (master)

### Steps to reproduce

1. Launch POS Awesome. For Opening Balances leave at 0.00 for all Payment Methods.
2. Do not do any transaction. Or make transaction and cancel such that there are no POS transactions.
3. Click on Close Shift then Submit.

### What is Expected?
Shift to be closed even when no POS transaction was made.

### What is actually happening?
Error is thrown. "Error: Data missing in table: POS Transactions"

### Additional context
Error seems to occur where no transactions were made or closing values are 0.00

### Screenshots
![e2-s1](https://user-images.githubusercontent.com/45001106/135743139-28cfaf82-626f-4c0f-88f4-fdfc954fc2df.png)
![e2-s2](https://user-images.githubusercontent.com/45001106/135743141-dda44214-db9a-4651-a452-b39655627c0e.png)

**Comment by yrestom** [comment]
In this case you can cancel and delete POS Opening Shift and then you can open new shift you need

**Comment by dmbabu** [comment]
> In this case you can cancel and delete POS Opening Shift and then you can open new shift if you need

Thanks for the great work with POS Awesome!

Yes. For now, I would like to do the following when Submit is clicked: 

Check if any POS Transactions exist for POS Opening Shift: 
if POS Transactions = 0
	Inform User
	Delete POS Opening Shift
else
	[...]	

Is this possible? Where can I insert this logic?

**Comment by yrestom** [comment]
https://github.com/yrestom/POS-Awesome/commit/5d1c7e9f7e3c66e2a5ba5c04de284294e7350aec
