### ISSUE TITLE
[BUG]: Wrong UOM selected when scanning a barcode for a Stock Item

### ISSUE THREAD

**Issue by KorucuTech** [yrestom/POS-Awesome#84]
Hello,

I was testing POS-Awesome with ERPNext 13.14.1 and I have this issue:

I created a Stock item that has multiple barcodes with different packaging 
When I scan either of the barcodes POS does not change the UOM and I have to change it manually.

Should it not use the UOM that the barcode is associated with?
It also pulls the wrong price for the UOM. i.e Price shown is not the price for the UOM displayed 

Thanks

![image](https://user-images.githubusercontent.com/6124584/144272211-3afbeeca-9b3c-4669-b248-9644f5c2f61f.png)

![image](https://user-images.githubusercontent.com/6124584/144272259-9df21638-531c-4948-b416-8bebe2df4d8e.png)

![image](https://user-images.githubusercontent.com/6124584/144273209-f2491b5c-9ed6-4b68-8ab0-3e07389c3721.png)

![image](https://user-images.githubusercontent.com/6124584/144273423-0c9eb549-ddd1-43e4-899c-3caa0f91f83b.png)

![image](https://user-images.githubusercontent.com/6124584/144273573-e864bb00-2015-4512-bbbf-35a13b8cc452.png)

**Comment by yrestom** [comment]
When searching, it shows the default UOM and its price, but when you add it to the card, it will take the price and the UOM associated with the barcode
