### ISSUE TITLE
On Open POS Serial No issue

### ISSUE THREAD

**Issue by bobzz-zone** [yrestom/POS-Awesome#9]
Hi,

i jsut experiencing error because of field not found
 unknown column `tabSerial No`.status

i check in the code there is really code for this and there is no status column in erpnext

it is on posawesome/posawesome/api/posapp.py line 336

so for temporary solution i removed it since im actually not using serial no

but please check it out

thanks

**Comment by yrestom** [comment]
Which Frappe and Erpnext version you have?

**Comment by bobzz-zone** [comment]
Hi 

we use version 12.4

thanks

**Comment by yrestom** [comment]
There is no problem found in the code
Please check in your site if in doctype "Serial No" there is a "status" field

**Comment by bobzz-zone** [comment]
Hi

the problem is im not seeing that field on ERPNext standard....
but will try to use newer version of erpnext then

Thanks
