### ISSUE TITLE
[BUG]: feat: Allow Print Last Invoice

### ISSUE THREAD

**Issue by MTAS101** [yrestom/POS-Awesome#90]
feat: Allow Print Last Invoice

I can not find it
Can you explain it?

**Comment by yrestom** [comment]
After you check "Allow Print Last Invoice" from Pos Profile and refresh POS Awesome, then submit a new Invoice from the POS then you will find in the Menu in the POS a new opinion show up "Print Last Invoice"
![Screen Shot 2021-12-18 at 14 40 17](https://user-images.githubusercontent.com/19572067/146639635-b931cd7d-ecdb-47a9-80be-e8d973b8f86f.png)

**Comment by MTAS101** [comment]
Installed on a new erpnext
The last invoice was not found
![1](https://user-images.githubusercontent.com/70178281/146645009-b244e0fb-359c-4b2d-b7fe-c20d17daf50c.png)
