### ISSUE TITLE
[BUG]: User POS Profile should be only for the ones he is on or Selected/Default set

### ISSUE THREAD

**Issue by Helkyd** [yrestom/POS-Awesome#95]
- Erpnext: 
- POS Awesome: 

### Steps to reproduce

1. Go to 'POS Awesome and when open it will show the SHIFT to Open'
2. Click on 'Check the list of PROFILES'

### What is actually happening?

System has 2 POS Profiles and each user only added to one... 
User 1 on Profile 1
User 2 on Profile 2

When opening the Shift it should check if user as **Default set** on which Profiles and show only the ones he is added or was added.
Right now users will be shown all Profiles and i can select the wrong Profile (ex. User 2 selects Profile 1 instead of).

**Comment by shelteradmin** [comment]
Did you found the solution for that. I am also facing the same issue

**Comment by Helkyd** [comment]
Actually no.. Left it for the owner to have a look and fix.

But I see no one else had this issue on that period and now you!

**Comment by yrestom** [comment]
For That issue, you can use user permissions to give access to the required profile

**Comment by shelteradmin** [comment]
Thanks, it worked. In default erpnext system the user permission is automatically handled. Here we have to make manually only.
